# -*- coding: utf-8 -*-
"""collect_dcgallery

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QpIr62x6tKPm9DNiR0Yw84k4gmZW7sDG

#1. 디씨인사이드_과거역학(2019-2021.09)

###키워드별 게시글 스크래핑
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
from urllib.parse import quote # URL 인코딩을 위해 import

def get_posts_from_page(url, headers):
    """
    지정된 URL 페이지에서 게시글 정보를 추출하고, 2018년 중단 조건을 확인합니다.
    (재시도 로직 포함)

    반환값: (page_data, stop_scraping)
           page_data: 수집된 게시글 데이터 리스트
           stop_scraping: 2018년도 게시글 발견 시 True
    """
    max_retries = 3 # 최대 3번까지 재시도
    retry_delay = 3   # 재시도 전 3초 대기

    for attempt in range(max_retries):
        try:
            # 타임아웃(10초)을 설정하여 무한 대기 방지
            response = requests.get(url, headers=headers, timeout=10)
            # HTTP 오류 코드가 반환되면 예외 발생
            response.raise_for_status()

            soup = BeautifulSoup(response.text, 'html.parser')
            # ⭐️ 공지사항(ub-content notice) 제외하고 일반 게시글만 선택
            post_list = soup.select('tr.ub-content.us-post:not(.notice)')

            if not post_list:
                return [], False # 게시글 없음, 중단 아님

            page_data = []
            stop_scraping = False # 2018년 중단 플래그

            for post in post_list:
                try:
                    num = post.select_one('.gall_num').text.strip()
                    # 숫자가 아닌 경우(광고 등) 건너뜀
                    if not num.isdigit():
                        continue

                    date_tag = post.select_one('.gall_date')
                    # title 속성이 없을 경우 text 사용 (YYYY.MM.DD 형식)
                    full_datetime = date_tag.get('title', date_tag.text.strip())
                    # datetime 형식에서 날짜 부분만 추출
                    date = full_datetime.split(' ')[0]

                    # ⭐️ 2018년 중단 조건 확인
                    year_str = date.split('.')[0]
                    if year_str.isdigit() and len(year_str) == 4:
                        year = int(year_str)
                        if year <= 2018:
                            print(f"\n[중단 조건 발견] {year}년 게시글({date})을 발견하여 스크래핑을 중단합니다.")
                            stop_scraping = True
                            break # 현재 페이지의 나머지 게시글 처리를 중단

                    # 2018년이 아니면 데이터 추출 계속
                    title_tag = post.select_one('.gall_tit a:not(.icon_pic):not(.icon_survey):not(.icon_voice)') # 아이콘 제외
                    if not title_tag:
                        continue

                    title = title_tag.text.strip()
                    # 댓글 수 태그 (em.reply_num)가 있으면 제거
                    reply_num_tag = title_tag.select_one("em.reply_num")
                    if reply_num_tag:
                        title = title.replace(reply_num_tag.text, '').strip() # 댓글 수 부분 제거

                    link = "https://gall.dcinside.com" + title_tag['href']

                    writer_tag = post.select_one('.gall_writer')
                    nickname = writer_tag.get('data-nick', '').strip()
                    ip = writer_tag.get('data-ip', '').strip()
                    writer = f"{nickname}({ip})" if ip else nickname

                    count = post.select_one('.gall_count').text.strip()
                    recommend = post.select_one('.gall_recommend').text.strip()

                    page_data.append([num, title, writer, date, count, recommend, link])

                except (AttributeError, KeyError, IndexError) as e:
                    # print(f"   - 특정 게시글 처리 중 오류 발생: {e}, 건너뜁니다.")
                    continue

            # 성공적으로 데이터를 가져왔다면 결과를 반환하고 함수 종료
            return page_data, stop_scraping

        # requests 관련 예외가 발생했을 때 실행
        except requests.exceptions.RequestException as e:
            print(f"페이지 요청 중 오류 발생 (시도 {attempt + 1}/{max_retries}): {e}")
            if attempt < max_retries - 1:
                print(f"{retry_delay}초 후 재시도합니다...")
                time.sleep(retry_delay)
            else:
                print("최종 접속에 실패했습니다.")

    # 모든 재시도가 실패하면 (빈 리스트, 중단 아님)을 반환
    return [], False

def scrape_keyword_data(keyword):
    """특정 키워드 하나에 대한 스크래핑을 수행하는 함수"""

    # URL에서 가져온 시작 search_pos 및 갤러리 ID
    search_pos = -17255549
    gallery_id = "divination"

    # URL 인코딩된 키워드 사용
    encoded_keyword = quote(keyword)
    base_url = f"https://gall.dcinside.com/board/lists/?id={gallery_id}&s_type=search_subject_memo&s_keyword={encoded_keyword}"

    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }

    all_posts = []
    current_search_pos = search_pos
    stop_all_scraping = False # 2018년 발견 시 전체 중단을 위한 플래그

    # search_pos가 음수인 동안, 그리고 중단 플래그가 False인 동안 계속 반복
    while current_search_pos < 0 and not stop_all_scraping:
        print(f"\n  [검색 단위 이동] search_pos: {current_search_pos}")

        page = 1
        processed_post_ids = set() # 현재 search_pos 내에서 처리된 게시글 번호 저장

        while not stop_all_scraping: # 2018년 발견 시 이 루프도 중단됨
            url_to_scrape = f"{base_url}&page={page}&search_pos={current_search_pos}"

            print(f"  - 스크래핑 중 (Page: {page})... ", end="") # 줄바꿈 없이 출력

            # ⭐️ 2018년 중단 플래그(page_stop_flag)를 함께 반환받음
            posts_on_page, page_stop_flag = get_posts_from_page(url_to_scrape, headers)

            # 1. 2018년 중단 조건이 감지된 경우
            if page_stop_flag:
                stop_all_scraping = True
                if posts_on_page:
                    print(f"{len(posts_on_page)}개 게시글 추가 후 중단.")
                    all_posts.extend(posts_on_page)
                break

            # 2. 페이지에 게시글이 없는 경우
            if not posts_on_page:
                print("게시글 없음. 현재 검색 단위 종료.")
                break

            # 3. 중복 페이지 감지
            current_page_ids = {post[0] for post in posts_on_page}
            if current_page_ids.issubset(processed_post_ids):
                 print(f"중복 페이지 감지됨. 현재 검색 단위 종료.")
                 break

            # 4. 새로운 게시글만 필터링하여 추가
            new_posts = []
            for post in posts_on_page:
                post_id = post[0]
                if post_id not in processed_post_ids:
                    new_posts.append(post)
                    processed_post_ids.add(post_id)

            if new_posts:
                print(f"{len(new_posts)}개 신규 수집.")
                all_posts.extend(new_posts)
            else:
                print("신규 게시글 없음. 현재 검색 단위 종료.")
                break

            page += 1
            time.sleep(0.7) # 서버 부하 감소

        # 다음 search_pos 블록으로 이동 (+10000)
        current_search_pos += 10000

    if stop_all_scraping:
        print(f"  ▶ 2018년 이전 게시글 도달. '{keyword}' 스크래핑 최종 중단.")
    else:
        print(f"  ▶ search_pos가 0 이상이 되어 '{keyword}' 스크래핑 최종 종료.")

    return all_posts


def main():
    """전체 키워드를 순회하는 메인 실행 함수"""

    # ⭐️ 스크래핑할 대상 키워드 리스트
    keywords = [
        "사주", "궁합", "타로", "천을귀인", "운세", "만세력",
        "신점", "GPT", "지피티", "사주 어플", "포스텔러",
        "점신", "사주 후기", "사주 앱", "엑스퍼트"
    ]

    print(f"총 {len(keywords)}개의 키워드 스크래핑을 시작합니다.")
    print("=" * 60)

    for keyword in keywords:
        print(f"\n\n============================================================")
        print(f" 🚀 현재 진행 중인 키워드: '{keyword}'")
        print(f"============================================================")

        final_posts = scrape_keyword_data(keyword)

        if final_posts:
            df = pd.DataFrame(final_posts, columns=['번호', '제목', '글쓴이', '작성일', '조회', '추천', '링크'])

            # ⭐️ 파일명에 동적으로 키워드 삽입
            file_name = f'디씨과거역학_{keyword}_게시글.csv'

            # 번호 기준으로 최종 중복 제거
            df.drop_duplicates(subset=['번호'], keep='first', inplace=True)

            df.to_csv(file_name, index=False, encoding='utf-8-sig')
            print(f"\n✅ [저장 완료] 총 {len(df)}개의 게시글 -> '{file_name}'")
        else:
            print(f"\n⚠️ [저장 실패] '{keyword}'에 대한 추출된 게시글이 없습니다.")

        # 디시인사이드 서버 부하(IP 차단 방지)를 위해 키워드 간 충분한 휴식
        print("\n다음 키워드로 넘어가기 전 5초간 대기합니다...")
        time.sleep(5)

    print("\n\n🎉 모든 키워드에 대한 스크래핑 작업이 완료되었습니다!")

if __name__ == "__main__":
    main()

"""### 본문 스크래핑"""

import pandas as pd
import requests
from bs4 import BeautifulSoup
import time
from tqdm import tqdm
import os

def get_post_content(url, headers, retries=3, delay=2):
    """
    주어진 URL에서 게시글 본문을 추출합니다.
    오류 발생 시 지정된 횟수만큼 재시도합니다.
    """
    for attempt in range(retries):
        try:
            # 타임아웃을 10초로 설정하여 무한 대기를 방지합니다.
            response = requests.get(url, headers=headers, timeout=10)
            # 4xx 또는 5xx 같은 HTTP 오류 코드가 반환되면 예외를 발생시킵니다.
            response.raise_for_status()
            soup = BeautifulSoup(response.text, 'html.parser')

            # 1. 본문 내용이 담긴 핵심 영역을 선택합니다.
            content_box = soup.select_one('div.gallview_contents div.writing_view_box')

            if content_box:
                # 2. 요소 내부의 텍스트를 추출하고, 줄바꿈으로 정리하여 반환합니다.
                return content_box.get_text(separator='\n', strip=True)
            else:
                return "본문을 찾을 수 없습니다."

        except requests.exceptions.RequestException as e:
            # 네트워크 관련 오류 발생 시 (너무 많은 출력 방지를 위해 콘솔 출력 최소화)
            if attempt < retries - 1:
                time.sleep(delay)
            else:
                return f"오류 발생: {e}" # 마지막 시도 실패 시 오류 메시지 반환

        except Exception as e:
            # 기타 예상치 못한 오류 발생 시
            return f"기타 오류: {e}" # 재시도 없이 즉시 오류 메시지 반환

def process_keyword_csv(keyword, chunk_size=5000):
    """특정 키워드에 대한 CSV 파일을 읽어 본문을 추가하고 분할 저장합니다."""

    input_file_path = f'디씨역학_{keyword}_게시글.csv'
    output_file_base_path = f'디씨역학_{keyword}_게시글_본문추가'

    # 해당 키워드의 원본 파일이 있는지 먼저 확인
    if not os.path.exists(input_file_path):
        print(f"⚠️ 건너뜀: '{input_file_path}' 파일을 찾을 수 없습니다.")
        return

    print(f"\n============================================================")
    print(f" 🚀 현재 진행 중인 키워드: '{keyword}'")
    print(f"============================================================")

    try:
        # 1. CSV 파일을 DataFrame으로 불러옵니다.
        df = pd.read_csv(input_file_path)

        # 2. 서버 차단을 피하기 위한 User-Agent 헤더
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
        }

        total_rows = len(df)
        print(f"총 {total_rows}개의 게시글에서 본문 추출을 시작합니다...")

        # 3. 데이터를 지정된 개수(chunk_size) 단위로 나누어 처리합니다.
        for i in range(0, total_rows, chunk_size):
            start_index = i
            end_index = min(i + chunk_size, total_rows)
            df_chunk = df.iloc[start_index:end_index].copy() # Warning 방지를 위해 copy() 사용

            part_num = (i // chunk_size) + 1
            output_file_path = f"{output_file_base_path}_part_{part_num}.csv"

            # [이어하기 기능] 이미 생성된 파일이 있다면 스크래핑 생략
            if os.path.exists(output_file_path):
                print(f"\nℹ️ 알림: '{output_file_path}' 파일이 이미 존재하여 건너뜁니다.")
                continue

            print(f"\n--- Part {part_num} 처리 중 ({start_index+1} ~ {end_index} 행) ---")

            # 4. 각 링크를 순회하며 본문 내용을 담을 리스트를 생성합니다.
            content_list = []

            # tqdm을 사용하여 진행 상황을 시각적으로 표시합니다.
            for url in tqdm(df_chunk['링크'], desc=f"Part {part_num} 본문 추출 중"):
                content = get_post_content(url, headers)
                content_list.append(content)
                # 서버에 부담을 주지 않기 위해 약간의 지연 시간을 줍니다.
                time.sleep(0.1)

            # 5. DataFrame 조각(chunk)에 '본문' 열을 추가합니다.
            df_chunk['본문'] = content_list

            # 6. 현재까지 처리된 조각(chunk)을 별도의 CSV 파일로 저장합니다.
            df_chunk.to_csv(output_file_path, index=False, encoding='utf-8-sig')
            print(f"✅ Part {part_num} 본문 추출 완료! '{output_file_path}' 파일에 저장되었습니다.")

    except Exception as e:
        print(f"❌ 스크립트 실행 중 오류가 발생했습니다 [{keyword}]: {e}")


def main():
    """메인 실행 함수"""

    # 💡 순회할 키워드 리스트
    keywords = [
        "사주", "궁합", "타로", "천을귀인", "운세", "만세력",
        "신점", "GPT", "지피티", "사주 어플", "포스텔러",
        "점신", "사주 후기", "사주 앱", "엑스퍼트"
    ]

    print(f"총 {len(keywords)}개의 키워드 파일에 대해 본문 추출 작업을 시작합니다.")

    for keyword in keywords:
        process_keyword_csv(keyword, chunk_size=5000)

    print(f"\n🎉 모든 키워드 파일의 본문 추출 작업이 완료되었습니다!")

if __name__ == "__main__":
    main()

"""###파일 통합"""

import pandas as pd
import os
import glob
import re

def combine_csv_for_keyword(keyword):
    """
    특정 키워드가 포함된 모든 part 파일을 찾아 하나로 병합 후 저장합니다.
    """
    # 1. 키워드가 포함되고 'part_'로 끝나는 모든 CSV 파일 찾기
    # 예: 폴더 내의 '*타로*part_*.csv' 에 해당하는 모든 파일을 찾습니다.
    file_pattern = f"*{keyword}*part_*.csv"
    file_paths = glob.glob(file_pattern)

    # 2. 해당 키워드의 part 파일이 없으면 다음 키워드로 넘어감
    if not file_paths:
        print(f"⚠️ '{keyword}' 키워드에 해당하는 파일이 없습니다. 건너뜁니다.")
        return

    # 3. 파일 이름에서 part_ 뒤의 숫자를 추출하여 올바른 순서(1, 2, 3...)로 정렬
    # (일반 정렬을 하면 part_10 이 part_2 보다 앞에 오기 때문에 숫자로 정렬)
    try:
        file_paths.sort(key=lambda x: int(re.search(r'part_(\d+)', x).group(1)))
    except Exception:
        file_paths.sort() # 만약 정규식 추출에 실패하면 기본 이름순 정렬

    print(f"\n▶ [{keyword}] 파일 병합 시작 (총 {len(file_paths)}개 파일 발견)")

    all_dataframes = []

    # 4. 정렬된 각 파일을 순서대로 읽어서 리스트에 추가
    for file_path in file_paths:
        try:
            df = pd.read_csv(file_path)
            all_dataframes.append(df)
            print(f"  - 로드 성공: {file_path}")
        except Exception as e:
            print(f"  - ❌ 로드 실패 ({file_path}): {e}")

    # 5. 데이터프레임 병합 및 새 파일로 저장
    if all_dataframes:
        combined_df = pd.concat(all_dataframes, ignore_index=True)

        # 저장할 통합 파일 이름 설정
        output_file_path = f'디씨과거역학_{keyword}_본문추가.csv'

        try:
            combined_df.to_csv(output_file_path, index=False, encoding='utf-8-sig')
            print(f"✅ [{keyword}] 병합 완료!")
            print(f"  - 저장 파일명: {output_file_path}")
            print(f"  - 총 데이터 수: {len(combined_df)}행")
        except Exception as e:
            print(f"❌ 파일 저장 중 오류 발생: {e}")
    else:
        print(f"[{keyword}] 병합할 데이터가 없습니다.")


def main():
    """메인 실행 함수"""

    # 💡 순회할 키워드 리스트
    keywords = [
        "사주", "궁합", "타로", "천을귀인", "운세", "만세력",
        "신점", "GPT", "지피티", "사주 어플", "포스텔러",
        "점신", "사주 후기", "사주 앱", "엑스퍼트"
    ]

    print(f"총 {len(keywords)}개 키워드에 대한 파일 병합 작업을 시작합니다.")
    print("=" * 60)

    for keyword in keywords:
        combine_csv_for_keyword(keyword)

    print("\n" + "=" * 60)
    print("🎉 모든 키워드의 파일 병합 작업이 완료되었습니다!")

# 코드 실행
if __name__ == "__main__":
    main()

"""#2. 디씨인사이드_역학(2021.09-2025.09)

###키워드별 게시글 스크래핑
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
from urllib.parse import urlparse, parse_qs, urlencode, quote

def get_posts_from_page(url, headers):
    """지정된 URL 페이지에서 게시글 정보를 추출합니다. (재시도 로직 추가)"""

    max_retries = 3 # 최대 3번까지 재시도
    retry_delay = 3   # 재시도 전 3초 대기

    for attempt in range(max_retries):
        try:
            # 타임아웃(10초)을 설정하여 무한 대기 방지
            response = requests.get(url, headers=headers, timeout=10)
            # HTTP 오류 코드가 반환되면 예외 발생
            response.raise_for_status()

            soup = BeautifulSoup(response.text, 'html.parser')
            # ⭐️ 공지사항(ub-content notice) 제외하고 일반 게시글만 선택
            post_list = soup.select('tr.ub-content.us-post:not(.notice)')

            # --- 게시글이 없는 경우 바로 빈 리스트 반환 ---
            if not post_list:
                return []

            page_data = []
            for post in post_list:
                try:
                    num = post.select_one('.gall_num').text.strip()
                    # 숫자가 아닌 경우(광고 등) 건너뜀
                    if not num.isdigit():
                        continue

                    title_tag = post.select_one('.gall_tit a:not(.icon_pic):not(.icon_survey):not(.icon_voice)') # 아이콘 제외
                    # 제목 태그가 없는 경우 건너뜀 (특수한 경우 대비)
                    if not title_tag:
                         continue

                    title = title_tag.text.strip()
                    # 댓글 수 태그 (em.reply_num)가 있으면 제거
                    reply_num_tag = title_tag.select_one("em.reply_num")
                    if reply_num_tag:
                         title = title.replace(reply_num_tag.text, '').strip() # 댓글 수 부분 제거

                    link = "https://gall.dcinside.com" + title_tag['href']

                    writer_tag = post.select_one('.gall_writer')
                    nickname = writer_tag.get('data-nick', '').strip()
                    ip = writer_tag.get('data-ip', '').strip()
                    writer = f"{nickname}({ip})" if ip else nickname

                    date_tag = post.select_one('.gall_date')
                    # title 속성이 없을 경우 text 사용 (YYYY.MM.DD 형식)
                    full_datetime = date_tag.get('title', date_tag.text.strip())
                    # datetime 형식에서 날짜 부분만 추출
                    date = full_datetime.split(' ')[0]

                    count = post.select_one('.gall_count').text.strip()
                    recommend = post.select_one('.gall_recommend').text.strip()

                    page_data.append([num, title, writer, date, count, recommend, link])

                except (AttributeError, KeyError, IndexError) as e:
                    # print(f"   - 특정 게시글 처리 중 오류 발생: {e}, 건너뜁니다.")
                    continue

            # 성공적으로 데이터를 가져왔다면 결과를 반환하고 함수 종료
            return page_data

        # requests 관련 예외가 발생했을 때 실행
        except requests.exceptions.RequestException as e:
            print(f"페이지 요청 중 오류 발생 (시도 {attempt + 1}/{max_retries}): {e}")
            if attempt < max_retries - 1:
                print(f"{retry_delay}초 후 재시도합니다...")
                time.sleep(retry_delay)
            else:
                print("최종 접속에 실패했습니다.")

    # 모든 재시도가 실패하면 빈 리스트를 반환
    return []

def scrape_keyword_data(keyword):
    """특정 키워드 하나에 대한 스크래핑을 수행하는 함수"""

    # URL에서 가져온 시작 search_pos (기존 코드 유지)
    search_pos = -9750048
    gallery_id = "divination_new1"

    # URL 인코딩된 키워드 사용
    encoded_keyword = quote(keyword)
    base_url = f"https://gall.dcinside.com/board/lists/?id={gallery_id}&s_type=search_subject_memo&s_keyword={encoded_keyword}"

    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }

    all_posts = []
    current_search_pos = search_pos

    # search_pos가 음수인 동안 계속 반복
    while current_search_pos < 0:
        print(f"\n  [검색 단위 이동] search_pos: {current_search_pos}")

        page = 1
        processed_post_ids = set() # 현재 search_pos 내에서 처리된 게시글 번호 저장

        while True:
            url_to_scrape = f"{base_url}&page={page}&search_pos={current_search_pos}"

            print(f"  - 스크래핑 중 (Page: {page})... ", end="") # 줄바꿈 없이 출력
            posts_on_page = get_posts_from_page(url_to_scrape, headers)

            # 1. 페이지에 게시글이 없는 경우
            if not posts_on_page:
                print("게시글 없음. 현재 검색 단위 종료.")
                break

            # 2. 현재 페이지의 모든 게시글이 이미 처리된 ID인 경우 (중복 페이지 감지)
            current_page_ids = {post[0] for post in posts_on_page}
            if current_page_ids.issubset(processed_post_ids):
                 print(f"중복 페이지 감지됨. 현재 검색 단위 종료.")
                 break

            # 3. 새로운 게시글만 필터링하여 추가
            new_posts = []
            for post in posts_on_page:
                post_id = post[0]
                if post_id not in processed_post_ids:
                    new_posts.append(post)
                    processed_post_ids.add(post_id)

            if new_posts:
                print(f"{len(new_posts)}개 신규 수집.")
                all_posts.extend(new_posts)
            else:
                print("신규 게시글 없음. 현재 검색 단위 종료.")
                break

            page += 1
            time.sleep(0.7) # 서버 부하 감소

        # 다음 search_pos 블록으로 이동 (+10000)
        current_search_pos += 10000

    print(f"  ▶ search_pos가 0 이상이 되어 '{keyword}' 스크래핑 최종 종료.")
    return all_posts


def main():
    """전체 키워드를 순회하는 메인 실행 함수"""

    # ⭐️ 스크래핑할 대상 키워드 리스트
    keywords = [
        "사주", "궁합", "타로", "천을귀인", "운세", "만세력",
        "신점", "GPT", "지피티", "사주 어플", "포스텔러",
        "점신", "사주 후기", "사주 앱", "엑스퍼트"
    ]

    print(f"총 {len(keywords)}개의 키워드 스크래핑을 시작합니다.")
    print("=" * 60)

    for keyword in keywords:
        print(f"\n\n============================================================")
        print(f" 🚀 현재 진행 중인 키워드: '{keyword}'")
        print(f"============================================================")

        final_posts = scrape_keyword_data(keyword)

        if final_posts:
            df = pd.DataFrame(final_posts, columns=['번호', '제목', '글쓴이', '작성일', '조회', '추천', '링크'])

            # ⭐️ 파일명에 동적으로 키워드 삽입 (요청하신 포맷 적용)
            file_name = f'디씨역학_{keyword}_게시글.csv'

            # 번호 기준으로 최종 중복 제거
            df.drop_duplicates(subset=['번호'], keep='first', inplace=True)

            df.to_csv(file_name, index=False, encoding='utf-8-sig')
            print(f"\n✅ [저장 완료] 총 {len(df)}개의 게시글 -> '{file_name}'")
        else:
            print(f"\n⚠️ [저장 실패] '{keyword}'에 대한 추출된 게시글이 없습니다.")

        # 디시인사이드 서버 부하(IP 차단 방지)를 위해 키워드 간 충분한 휴식
        print("\n다음 키워드로 넘어가기 전 5초간 대기합니다...")
        time.sleep(5)

    print("\n\n🎉 모든 키워드에 대한 스크래핑 작업이 완료되었습니다!")

if __name__ == "__main__":
    main()

"""### 본문 스크래핑"""

import pandas as pd
import requests
from bs4 import BeautifulSoup
import time
from tqdm import tqdm
import os

def get_post_content(url, headers, retries=3, delay=2):
    """
    주어진 URL에서 게시글 본문을 추출합니다.
    오류 발생 시 지정된 횟수만큼 재시도합니다.
    """
    for attempt in range(retries):
        try:
            # 타임아웃을 10초로 설정하여 무한 대기를 방지합니다.
            response = requests.get(url, headers=headers, timeout=10)
            # 4xx 또는 5xx 같은 HTTP 오류 코드가 반환되면 예외를 발생시킵니다.
            response.raise_for_status()
            soup = BeautifulSoup(response.text, 'html.parser')

            # 1. 본문 내용이 담긴 핵심 영역을 선택합니다.
            content_box = soup.select_one('div.gallview_contents div.writing_view_box')

            if content_box:
                # 2. 요소 내부의 텍스트를 추출하고, 줄바꿈으로 정리하여 반환합니다.
                return content_box.get_text(separator='\n', strip=True)
            else:
                return "본문을 찾을 수 없습니다."

        except requests.exceptions.RequestException as e:
            # 네트워크 관련 오류 발생 시 (너무 많은 출력 방지를 위해 콘솔 출력 최소화)
            if attempt < retries - 1:
                time.sleep(delay)
            else:
                return f"오류 발생: {e}" # 마지막 시도 실패 시 오류 메시지 반환

        except Exception as e:
            # 기타 예상치 못한 오류 발생 시
            return f"기타 오류: {e}" # 재시도 없이 즉시 오류 메시지 반환

def process_keyword_csv(keyword, chunk_size=5000):
    """특정 키워드에 대한 CSV 파일을 읽어 본문을 추가하고 분할 저장합니다."""

    input_file_path = f'디씨역학_{keyword}_게시글.csv'
    output_file_base_path = f'디씨역학_{keyword}_게시글_본문추가'

    # 해당 키워드의 원본 파일이 있는지 먼저 확인
    if not os.path.exists(input_file_path):
        print(f"⚠️ 건너뜀: '{input_file_path}' 파일을 찾을 수 없습니다.")
        return

    print(f"\n============================================================")
    print(f" 🚀 현재 진행 중인 키워드: '{keyword}'")
    print(f"============================================================")

    try:
        # 1. CSV 파일을 DataFrame으로 불러옵니다.
        df = pd.read_csv(input_file_path)

        # 2. 서버 차단을 피하기 위한 User-Agent 헤더
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
        }

        total_rows = len(df)
        print(f"총 {total_rows}개의 게시글에서 본문 추출을 시작합니다...")

        # 3. 데이터를 지정된 개수(chunk_size) 단위로 나누어 처리합니다.
        for i in range(0, total_rows, chunk_size):
            start_index = i
            end_index = min(i + chunk_size, total_rows)
            df_chunk = df.iloc[start_index:end_index].copy() # Warning 방지를 위해 copy() 사용

            part_num = (i // chunk_size) + 1
            output_file_path = f"{output_file_base_path}_part_{part_num}.csv"

            # [이어하기 기능] 이미 생성된 파일이 있다면 스크래핑 생략
            if os.path.exists(output_file_path):
                print(f"\nℹ️ 알림: '{output_file_path}' 파일이 이미 존재하여 건너뜁니다.")
                continue

            print(f"\n--- Part {part_num} 처리 중 ({start_index+1} ~ {end_index} 행) ---")

            # 4. 각 링크를 순회하며 본문 내용을 담을 리스트를 생성합니다.
            content_list = []

            # tqdm을 사용하여 진행 상황을 시각적으로 표시합니다.
            for url in tqdm(df_chunk['링크'], desc=f"Part {part_num} 본문 추출 중"):
                content = get_post_content(url, headers)
                content_list.append(content)
                # 서버에 부담을 주지 않기 위해 약간의 지연 시간을 줍니다.
                time.sleep(0.1)

            # 5. DataFrame 조각(chunk)에 '본문' 열을 추가합니다.
            df_chunk['본문'] = content_list

            # 6. 현재까지 처리된 조각(chunk)을 별도의 CSV 파일로 저장합니다.
            df_chunk.to_csv(output_file_path, index=False, encoding='utf-8-sig')
            print(f"✅ Part {part_num} 본문 추출 완료! '{output_file_path}' 파일에 저장되었습니다.")

    except Exception as e:
        print(f"❌ 스크립트 실행 중 오류가 발생했습니다 [{keyword}]: {e}")


def main():
    """메인 실행 함수"""

    # 💡 순회할 키워드 리스트
    keywords = [
        "사주", "궁합", "타로", "천을귀인", "운세", "만세력",
        "신점", "GPT", "지피티", "사주 어플", "포스텔러",
        "점신", "사주 후기", "사주 앱", "엑스퍼트"
    ]

    print(f"총 {len(keywords)}개의 키워드 파일에 대해 본문 추출 작업을 시작합니다.")

    for keyword in keywords:
        process_keyword_csv(keyword, chunk_size=5000)

    print(f"\n🎉 모든 키워드 파일의 본문 추출 작업이 완료되었습니다!")

if __name__ == "__main__":
    main()

"""###파일 통합"""

import pandas as pd
import os
import glob
import re

def combine_csv_for_keyword(keyword):
    """
    특정 키워드가 포함된 모든 part 파일을 찾아 하나로 병합 후 저장합니다.
    """
    # 1. 키워드가 포함되고 'part_'로 끝나는 모든 CSV 파일 찾기
    # 예: 폴더 내의 '*타로*part_*.csv' 에 해당하는 모든 파일을 찾습니다.
    file_pattern = f"*{keyword}*part_*.csv"
    file_paths = glob.glob(file_pattern)

    # 2. 해당 키워드의 part 파일이 없으면 다음 키워드로 넘어감
    if not file_paths:
        print(f"⚠️ '{keyword}' 키워드에 해당하는 파일이 없습니다. 건너뜁니다.")
        return

    # 3. 파일 이름에서 part_ 뒤의 숫자를 추출하여 올바른 순서(1, 2, 3...)로 정렬
    # (일반 정렬을 하면 part_10 이 part_2 보다 앞에 오기 때문에 숫자로 정렬)
    try:
        file_paths.sort(key=lambda x: int(re.search(r'part_(\d+)', x).group(1)))
    except Exception:
        file_paths.sort() # 만약 정규식 추출에 실패하면 기본 이름순 정렬

    print(f"\n▶ [{keyword}] 파일 병합 시작 (총 {len(file_paths)}개 파일 발견)")

    all_dataframes = []

    # 4. 정렬된 각 파일을 순서대로 읽어서 리스트에 추가
    for file_path in file_paths:
        try:
            df = pd.read_csv(file_path)
            all_dataframes.append(df)
            print(f"  - 로드 성공: {file_path}")
        except Exception as e:
            print(f"  - ❌ 로드 실패 ({file_path}): {e}")

    # 5. 데이터프레임 병합 및 새 파일로 저장
    if all_dataframes:
        combined_df = pd.concat(all_dataframes, ignore_index=True)

        # 저장할 통합 파일 이름 설정
        output_file_path = f'디씨역학_{keyword}_본문추가.csv'

        try:
            combined_df.to_csv(output_file_path, index=False, encoding='utf-8-sig')
            print(f"✅ [{keyword}] 병합 완료!")
            print(f"  - 저장 파일명: {output_file_path}")
            print(f"  - 총 데이터 수: {len(combined_df)}행")
        except Exception as e:
            print(f"❌ 파일 저장 중 오류 발생: {e}")
    else:
        print(f"[{keyword}] 병합할 데이터가 없습니다.")


def main():
    """메인 실행 함수"""

    # 💡 순회할 키워드 리스트
    keywords = [
        "사주", "궁합", "타로", "천을귀인", "운세", "만세력",
        "신점", "GPT", "지피티", "사주 어플", "포스텔러",
        "점신", "사주 후기", "사주 앱", "엑스퍼트"
    ]

    print(f"총 {len(keywords)}개 키워드에 대한 파일 병합 작업을 시작합니다.")
    print("=" * 60)

    for keyword in keywords:
        combine_csv_for_keyword(keyword)

    print("\n" + "=" * 60)
    print("🎉 모든 키워드의 파일 병합 작업이 완료되었습니다!")

# 코드 실행
if __name__ == "__main__":
    main()