# -*- coding: utf-8 -*-
"""collect_fmkorea

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wJKz6mhtLCqO20ZUO19Lg-2EDZdpX5Kp

#1. 에펨코리아

###키워드별 게시글 스크래핑
"""

import csv
import time
from datetime import datetime
import urllib.parse
from bs4 import BeautifulSoup

# URL에서 '번호'를 추출하기 위한 라이브러리
from urllib.parse import urlparse, parse_qs

# 셀레니움 라이브러리 임포트
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

# 1. 날짜 형식 변환 함수
def format_date(date_string):
    """
    fmkorea의 날짜 형식을 'YYYY.MM.DD'로 변환합니다.
    - 'HH:MM' 형식은 오늘 날짜로 변환
    - 'YY.MM.DD' 형식은 '20YY.MM.DD'로 변환
    """
    try:
        if ':' in date_string:  # '13:05'와 같은 시간 형식
            return datetime.now().strftime('%Y.%m.%d')
        elif date_string.count('.') == 2:  # '25.11.10' 또는 '2025.11.10'
            parts = date_string.split('.')
            if len(parts[0]) == 2:  # 'YY' 형식
                return f"20{parts[0]}.{parts[1]}.{parts[2]}"
            return date_string
        else:
            return date_string
    except Exception:
        return date_string

# 2. CSV 저장 함수 (카테고리명 반영)
def save_to_csv(data, category, keyword):
    """
    수집된 데이터를 CSV 파일로 저장합니다.
    파일 이름: '에펨코리아_카테고리명_키워드.csv'
    """
    # 파일명에 사용할 수 없는 문자가 카테고리명에 있을 경우 언더스코어로 대체
    safe_category = category.replace("/", "_").replace("\\", "_")
    filename = f"에펨코리아_{safe_category}_{keyword}.csv"
    headers = ['번호', '제목', '링크', '글쓴이', '작성일', '조회']

    try:
        with open(filename, 'w', encoding='utf-8-sig', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(headers)
            writer.writerows(data)
        print(f"\n✅ 성공: '{filename}' 파일로 저장이 완료되었습니다.")
    except Exception as e:
        print(f"\n❌ 오류: 파일 저장 중 문제가 발생했습니다. {e}")

# 3. 핵심 스크래핑 함수
def scrape_keyword(driver, category_name, board_id, keyword):
    """
    (Selenium) 새 HTML 구조(테이블)에 맞춰 검색하고 페이징하며 스크래핑합니다.
    """
    scraped_links = set()
    all_results = []
    page = 1
    encoded_keyword = urllib.parse.quote(keyword)

    print(f"\n--- [{category_name}] 게시판에서 '{keyword}' 키워드 검색 및 스크래핑 시작 ---")

    while True:
        # URL에 제공받은 게시판 ID(mid) 적용
        target_url = f"https://www.fmkorea.com/search.php?mid={board_id}&search_keyword={encoded_keyword}&search_target=title_content&page={page}"
        print(f"Scraping page {page}: {target_url}")

        try:
            driver.get(target_url)
            time.sleep(1.5) # 페이지 로드를 위해 잠시 대기

            soup = BeautifulSoup(driver.page_source, 'html.parser')
            posts = soup.select("table.bd_lst > tbody > tr")

            if not posts:
                print(f"Page {page}: 데이터가 없습니다. 스크래핑을 종료합니다.")
                break

            new_data_found_on_this_page = False
            page_results = []

            for post in posts:
                try:
                    post_classes = post.get('class', [])
                    if 'notice' in post_classes or 'ad_wrapper' in post_classes:
                        continue

                    title_element = post.select_one("td.title > a.hx")
                    author_element = post.select_one("td.author a")
                    date_element = post.select_one("td.time")
                    m_no_elements = post.select("td.m_no")
                    views_element = m_no_elements[0] if m_no_elements else None

                    if not title_element or not author_element or not date_element or not views_element:
                        continue

                    link = title_element['href']
                    if not link.startswith('http'):
                        link = "https://www.fmkorea.com" + link

                    if link in scraped_links:
                        continue

                    new_data_found_on_this_page = True
                    scraped_links.add(link)

                    parsed_url = urlparse(link)
                    query_params = parse_qs(parsed_url.query)
                    number = query_params.get('document_srl', [None])[0]

                    if number is None:
                        number = link.split('/')[-1].split('?')[0]

                    title = title_element.text.strip()
                    author = author_element.text.strip()
                    date_raw = date_element.text.strip()
                    date = format_date(date_raw)
                    views = views_element.text.strip().replace(',', '')

                    page_results.append([number, title, link, author, date, views])

                except Exception as e:
                    print(f"  - (오류) 게시물 1개 파싱 중 문제 발생: {e}")

            if not new_data_found_on_this_page and page > 1:
                 print(f"Page {page}: 새로운 데이터가 없고 중복 데이터만 감지되었습니다. 스크래핑을 종료합니다.")
                 break

            if not page_results and not new_data_found_on_this_page:
                print(f"Page {page}:에서 추가 데이터를 찾지 못했습니다. 스크래핑을 종료합니다.")
                break

            all_results.extend(page_results)
            page += 1

        except Exception as e:
            print(f"❌ (오류) Page {page} 파싱 중 예기치 못한 문제 발생: {e}")
            break

    if all_results:
        save_to_csv(all_results, category_name, keyword)
    else:
        print(f"\n--- [{category_name}] 게시판에서 '{keyword}'에 대한 검색 결과가 없습니다. ---")


# 4. 메인 실행 함수
def main():
    """
    여러 게시판 카테고리와 검색 키워드를 순회하며 스크래핑을 실행합니다.
    """

    # 검색할 키워드 리스트
    search_keywords = [
        "궁합", "네이버 엑스퍼트", "만세력", "사주 후기", "사주 어플",
        "사주 앱", "신점", "사주", "운세", "점신",
        "천을귀인", "타로", "포스텔러", "사주팔자", "gpt 사주"
    ]

    # 60개 카테고리 전체 활성화 매핑
    categories = {
        "humor": "유머이슈",
        "politics": "정치시사",
        "digital": "디지털",
        "mystery": "미스테리공포",
        "football_news": "축구소식통",
        "football_world": "해외축구",
        "football_korean": "국내축구",
        "baseball": "야구",
        "basketball": "농구",
        "other_sports": "기타스포츠",
        "stock": "주식",
        "freedeal": "자유쇼핑",
        "coin": "가상화폐",
        "realestate": "부동산",
        "afreecatv": "숲(SOOP)",
        "ib": "치지직",
        "starcraft": "스타크래프트",
        "movietv": "영화티비",
        "vtuber": "버튜버",
        "hiphop": "힙합",
        "mangawebtoon": "웹툰만화",
        "assapig": "운동건강",
        "personacon": "퍼스나콘",
        "lol": "롤",
        "other_game": "피씨콘솔게임",
        "mgame": "모바일게임",
        "gersang": "거상",
        "nikke": "니케",
        "df": "던파",
        "diablo": "디아블로",
        "lostark": "로스트아크",
        "mabinogi": "마비노기M",
        "maple": "메이플",
        "wutheringwaves": "명조",
        "baramy": "바람의나라",
        "valorant": "발로란트",
        "bluearchive": "블루아카이브",
        "gf": "소녀전선",
        "starrail": "스타레일",
        "genshin": "원신",
        "baseball_game": "야구게임",
        "eternalreturn": "이터널리턴",
        "uma": "우마무스메",
        "tft": "롤토체스",
        "poe": "패스오브엑자일",
        "wow": "와우",
        "zenless": "젠레스",
        "fashion": "패션",
        "car": "자동차",
        "love": "연애상담",
        "free": "자유",
        "job": "직장",
        "study": "공부",
        "girlgroup": "걸그룹",
        "subculture": "오덕양성소",
        "starfree": "연예인잡담",
        "hotdeal": "핫딜",
        "food": "음식",
        "girlstar": "여자연예인",
        "animal": "동식물"
    }

    # --- Selenium 드라이버 설정 ---
    try:
        print("Selenium Chrome 드라이버를 설정합니다...")
        service = Service(ChromeDriverManager().install())
        options = webdriver.ChromeOptions()
        # options.add_argument('--headless') # 백그라운드 실행을 원하면 주석 해제
        # options.add_argument('--disable-gpu')

        driver = webdriver.Chrome(service=service, options=options)
        print("드라이버 설정 완료.")
    except Exception as e:
        print(f"❌ 치명적 오류: Selenium 드라이버 설정에 실패했습니다. {e}")
        return
    # -----------------------------

    print(f"총 {len(categories)}개의 카테고리와 {len(search_keywords)}개의 키워드 조합으로 스크래핑을 시작합니다.")
    print("="*50)

    try:
        # 카테고리 반복 (board_id를 mid로 사용)
        for board_id, category_name in categories.items():
            print(f"\n\n▶▶▶ 현재 카테고리 작업 중: {category_name} (게시판 ID: {board_id}) ◀◀◀")

            # 카테고리 내에서 키워드 반복
            for keyword in search_keywords:
                scrape_keyword(driver, category_name, board_id, keyword)
                time.sleep(3) # 키워드 검색 사이에 3초 대기 (서버 차단 방지)

            time.sleep(5) # 카테고리가 바뀔 때는 5초 대기

    except Exception as e:
        print(f"❌ 스크래핑 메인 루프에서 오류 발생: {e}")
    finally:
        driver.quit()
        print("\n" + "="*50)
        print("모든 카테고리와 키워드에 대한 작업이 완료되었습니다. 브라우저를 종료합니다.")

if __name__ == "__main__":
    main()

"""### 본문 스크래핑"""

import csv
import time
import os
from datetime import datetime
import urllib.parse
from bs4 import BeautifulSoup
from urllib.parse import urlparse, parse_qs
from tqdm import tqdm

# 셀레니움 라이브러리 임포트
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.common.exceptions import WebDriverException

# ==========================================
# 1단계: 유틸리티 함수 (날짜 포맷)
# ==========================================
def format_date(date_string):
    """fmkorea의 날짜 형식을 'YYYY.MM.DD'로 변환합니다."""
    try:
        if ':' in date_string:
            return datetime.now().strftime('%Y.%m.%d')
        elif date_string.count('.') == 2:
            parts = date_string.split('.')
            if len(parts[0]) == 2:
                return f"20{parts[0]}.{parts[1]}.{parts[2]}"
            return date_string
        else:
            return date_string
    except Exception:
        return date_string

def get_safe_filename(category, keyword, suffix=""):
    """파일 이름에 사용할 수 없는 문자를 제거한 안전한 파일명을 반환합니다."""
    safe_category = category.replace("/", "_").replace("\\", "_")
    return f"에펨코리아_{safe_category}_{keyword}{suffix}.csv"

# ==========================================
# 2단계: 게시글 [목록] 스크래핑 함수
# ==========================================
def scrape_post_list(driver, category_name, board_id, keyword):
    """(Selenium) 새 HTML 구조(테이블)에 맞춰 검색하고 페이징하며 목록을 스크래핑합니다."""
    scraped_links = set()
    all_results = []
    page = 1
    encoded_keyword = urllib.parse.quote(keyword)
    filename = get_safe_filename(category_name, keyword)

    # 이미 목록 파일이 있으면 건너뛰기
    if os.path.exists(filename):
        print(f"  ℹ️ [목록 수집 패스] '{filename}' 파일이 이미 존재합니다.")
        return True # 성공(파일 존재)으로 간주

    print(f"\n▶ [{category_name}] '{keyword}' 목록 스크래핑 시작")

    while True:
        target_url = f"https://www.fmkorea.com/search.php?mid={board_id}&search_keyword={encoded_keyword}&search_target=title_content&page={page}"

        try:
            driver.get(target_url)
            time.sleep(1.5)

            soup = BeautifulSoup(driver.page_source, 'html.parser')
            posts = soup.select("table.bd_lst > tbody > tr")

            if not posts:
                print(f"  - Page {page}: 데이터가 없습니다. 목록 수집 종료.")
                break

            new_data_found_on_this_page = False
            page_results = []

            for post in posts:
                try:
                    post_classes = post.get('class', [])
                    if 'notice' in post_classes or 'ad_wrapper' in post_classes:
                        continue

                    title_element = post.select_one("td.title > a.hx")
                    author_element = post.select_one("td.author a")
                    date_element = post.select_one("td.time")
                    m_no_elements = post.select("td.m_no")
                    views_element = m_no_elements[0] if m_no_elements else None

                    if not title_element or not author_element or not date_element or not views_element:
                        continue

                    link = title_element['href']
                    if not link.startswith('http'):
                        link = "https://www.fmkorea.com" + link

                    if link in scraped_links:
                        continue

                    new_data_found_on_this_page = True
                    scraped_links.add(link)

                    parsed_url = urlparse(link)
                    query_params = parse_qs(parsed_url.query)
                    number = query_params.get('document_srl', [None])[0]

                    if number is None:
                        number = link.split('/')[-1].split('?')[0]

                    title = title_element.text.strip()
                    author = author_element.text.strip()
                    date_raw = date_element.text.strip()
                    date = format_date(date_raw)
                    views = views_element.text.strip().replace(',', '')

                    page_results.append([number, title, link, author, date, views])

                except Exception as e:
                    pass

            if not new_data_found_on_this_page and page > 1:
                 print(f"  - Page {page}: 중복 데이터만 감지. 목록 수집 종료.")
                 break

            if not page_results and not new_data_found_on_this_page:
                break

            all_results.extend(page_results)
            print(f"  - Page {page} 수집 완료 ({len(page_results)}개)")
            page += 1

        except Exception as e:
            print(f"❌ (오류) Page {page} 파싱 중 문제 발생: {e}")
            break

    if all_results:
        headers = ['번호', '제목', '링크', '글쓴이', '작성일', '조회']
        try:
            with open(filename, 'w', encoding='utf-8-sig', newline='') as f:
                writer = csv.writer(f)
                writer.writerow(headers)
                writer.writerows(all_results)
            print(f"✅ [목록 저장 완료] '{filename}'")
            return True
        except Exception as e:
            print(f"❌ [목록 저장 오류] {e}")
            return False
    else:
        print(f"  - [{category_name}] '{keyword}' 검색 결과가 없습니다.")
        return False

# ==========================================
# 3단계: 게시글 [본문] 스크래핑 함수
# ==========================================
def get_content_from_link(driver, link):
    """Selenium 드라이버로 개별 링크에 접속하여 본문 내용을 스크래핑합니다."""
    try:
        driver.get(link)
        time.sleep(1.5)
        post_soup = BeautifulSoup(driver.page_source, 'html.parser')
        content_element = post_soup.select_one("div.rd_body .xe_content")

        if content_element:
            return content_element.text.strip().replace('\n', ' ')
        else:
            return "본문 수집 실패"
    except WebDriverException as e:
        return "WebDriver 오류"
    except Exception as e:
        return "본문 수집 오류"

def process_csv_for_content(driver, category_name, keyword):
    """저장된 목록 CSV를 읽고 본문을 추가하여 새 파일로 저장합니다."""
    input_filename = get_safe_filename(category_name, keyword)
    output_filename = get_safe_filename(category_name, keyword, "+본문")

    if os.path.exists(output_filename):
        print(f"  ℹ️ [본문 수집 패스] '{output_filename}' 파일이 이미 존재합니다.")
        return

    original_data = []
    headers = []

    try:
        with open(input_filename, 'r', encoding='utf-8-sig') as f:
            reader = csv.reader(f)
            headers = next(reader)
            original_data = list(reader)
    except FileNotFoundError:
        return # 목록 파일이 없는 경우 패스
    except Exception as e:
        print(f"❌ '{input_filename}' 파일 읽기 오류: {e}")
        return

    try:
        link_column_index = headers.index("링크")
    except ValueError:
        print(f"❌ '{input_filename}'에 '링크' 컬럼이 없습니다.")
        return

    print(f"▶ [{category_name}] '{keyword}' 본문 추출 시작 ({len(original_data)}개)")

    new_data = [headers + ["본문"]]

    for i, row in enumerate(tqdm(original_data, desc="본문 수집 중")):
        link_to_visit = row[link_column_index]
        content = get_content_from_link(driver, link_to_visit)
        new_data.append(row + [content])
        time.sleep(0.5) # 과부하 방지

    if len(new_data) > 1:
        try:
            with open(output_filename, 'w', encoding='utf-8-sig', newline='') as f:
                writer = csv.writer(f)
                writer.writerows(new_data)
            print(f"✅ [본문 저장 완료] '{output_filename}'")
        except Exception as e:
            print(f"❌ '{output_filename}' 파일 저장 오류: {e}")

# ==========================================
# 4단계: 메인 실행부
# ==========================================
def main():
    search_keywords = [
        "사주", "궁합", "타로", "천을귀인", "운세", "만세력",
        "신점", "GPT", "지피티", "사주 어플", "포스텔러",
        "점신", "사주 후기", "사주 앱", "엑스퍼트"
    ]

    categories = {
        "humor": "유머이슈", "politics": "정치시사", "digital": "디지털",
        "mystery": "미스테리공포", "football_news": "축구소식통", "football_world": "해외축구",
        "football_korean": "국내축구", "baseball": "야구", "basketball": "농구",
        "other_sports": "기타스포츠", "stock": "주식", "freedeal": "자유쇼핑",
        "coin": "가상화폐", "realestate": "부동산", "afreecatv": "숲(SOOP)",
        "ib": "치지직", "starcraft": "스타크래프트", "movietv": "영화티비",
        "vtuber": "버튜버", "hiphop": "힙합", "mangawebtoon": "웹툰만화",
        "assapig": "운동건강", "personacon": "퍼스나콘", "lol": "롤",
        "other_game": "피씨콘솔게임", "mgame": "모바일게임", "gersang": "거상",
        "nikke": "니케", "df": "던파", "diablo": "디아블로",
        "lostark": "로스트아크", "mabinogi": "마비노기M", "maple": "메이플",
        "wutheringwaves": "명조", "baramy": "바람의나라", "valorant": "발로란트",
        "bluearchive": "블루아카이브", "gf": "소녀전선", "starrail": "스타레일",
        "genshin": "원신", "baseball_game": "야구게임", "eternalreturn": "이터널리턴",
        "uma": "우마무스메", "tft": "롤토체스", "poe": "패스오브엑자일",
        "wow": "와우", "zenless": "젠레스", "fashion": "패션",
        "car": "자동차", "love": "연애상담", "free": "자유",
        "job": "직장", "study": "공부", "girlgroup": "걸그룹",
        "subculture": "오덕양성소", "starfree": "연예인잡담", "hotdeal": "핫딜",
        "food": "음식", "girlstar": "여자연예인", "animal": "동식물"
    }

    try:
        print("Selenium Chrome 드라이버를 설정합니다...")
        service = Service(ChromeDriverManager().install())
        options = webdriver.ChromeOptions()
        # options.add_argument('--headless')
        driver = webdriver.Chrome(service=service, options=options)
        print("드라이버 설정 완료.\n")
    except Exception as e:
        print(f"❌ 드라이버 설정 실패: {e}")
        return

    print(f"총 {len(categories)}개 카테고리 x {len(search_keywords)}개 키워드 작업을 시작합니다.")
    print("="*60)

    try:
        for board_id, category_name in categories.items():
            print(f"\n\n============================================================")
            print(f" 📂 현재 카테고리: {category_name} (게시판 ID: {board_id})")
            print(f"============================================================")

            for keyword in search_keywords:
                # 1단계: 목록 수집 (이미 있으면 패스됨)
                has_data = scrape_post_list(driver, category_name, board_id, keyword)

                # 2단계: 목록이 존재하면 본문 추출 실행 (이미 있으면 패스됨)
                if has_data:
                    process_csv_for_content(driver, category_name, keyword)

                time.sleep(2) # 키워드 간 대기

            time.sleep(5) # 카테고리 간 대기

    except Exception as e:
        print(f"❌ 메인 루프 오류: {e}")
    finally:
        driver.quit()
        print("\n" + "="*60)
        print("🎉 모든 작업이 완료되었습니다. 브라우저를 종료합니다.")

if __name__ == "__main__":
    main()