# -*- coding: utf-8 -*-
"""platform_comparison

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rmXzhxylrSKBSRG3A36JOPSgvlSLLnbv

# 플랫폼 비교 분석
"""

# 0. 폰트 설치
!pip install konlpy
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.font_manager as fm
from matplotlib.gridspec import GridSpec
import numpy as np
import math

# 1. 폰트 설정
plt.rc('font', family='NanumBarunGothic')
plt.rcParams['axes.unicode_minus'] = False

"""### 그림 1 플랫폼별 데이터 비율(운세 서비스 후기 분류 전후 비교)"""

# [1] 폰트 설치 (코랩용)
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.font_manager as fm

# ------------------------------------------------------------------
# [설정] 폰트 및 스타일
# ------------------------------------------------------------------
font_path = '/usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf'
fm.fontManager.addfont(font_path)
sns.set(font='NanumBarunGothic', rc={"axes.unicode_minus":False}, style='whitegrid')
plt.rc('font', family='NanumBarunGothic')

# ------------------------------------------------------------------
# [데이터 로드] 전처리가 완료된 두 개의 파일 각각 호출
# ------------------------------------------------------------------
# [A] 전체 데이터
file_total = '/content/drive/MyDrive/0. 커뮤니티 분석/0. 전처리 데이터/tagged_result_final_v26_cleansed.csv'
df_total = pd.read_csv(file_total)

# [B] 운세 서비스 후기 데이터
file_pure = '/content/drive/MyDrive/0. 커뮤니티 분석/0. 전처리 데이터/filtered_reviews_data_v26_cleansed.csv'
df_pure = pd.read_csv(file_pure)

# 시각화 함수에서 사용할 수 있도록 '사이트' 칼럼을 'Platform'으로 복사
if 'Platform' not in df_total.columns:
    df_total['Platform'] = df_total['사이트']
if 'Platform' not in df_pure.columns:
    df_pure['Platform'] = df_pure['사이트']

print(f"✅ 데이터셋 준비 완료")
print(f" - [A] 전체 분석 대상 데이터: {len(df_total):,}건")
print(f" - [B] 운세 서비스 후기 데이터: {len(df_pure):,}건")

# ------------------------------------------------------------------
# [함수] 스마트 도넛 차트 그리기 (겹침 방지 + 범례 강화)
# ------------------------------------------------------------------
def plot_smart_donut(ax, data_series, title, colors_dict):
    # 1. 데이터 정렬 (큰 순서대로)
    data = data_series.sort_values(ascending=False)

    # 2. 색상 매핑
    colors = [colors_dict.get(x, '#999999') for x in data.index]

    # 3. 차트 그리기 (라벨은 일단 None으로 설정하여 자동 출력을 막음)
    wedges, texts, autotexts = ax.pie(
        data,
        labels=None,  # ★ 겹침 방지를 위해 여기서 라벨을 끄고 범례로 대체합니다
        autopct='%1.1f%%',
        startangle=90,
        counterclock=False, # 시계 방향으로 정렬
        colors=colors,
        pctdistance=0.85,
        wedgeprops={'edgecolor': 'white', 'linewidth': 2}
    )

    # 4. 도넛 모양 만들기
    centre_circle = plt.Circle((0,0), 0.60, fc='white')
    ax.add_artist(centre_circle)

    # 5. [핵심] 작은 파이 조각의 % 텍스트 숨기기 (겹침 방지)
    threshold = 3.0 # 3% 미만은 그래프 위에서 글자 숨김
    for i, p in enumerate(wedges):
        ang = (p.theta2 - p.theta1) / 360 * 100
        if ang < threshold:
            autotexts[i].set_visible(False) # % 텍스트 숨기기
        else:
            autotexts[i].set_fontsize(18)
            autotexts[i].set_fontweight('bold')
            autotexts[i].set_color('white') # 가독성을 위해 흰색 글씨

    # 6. 타이틀 설정
    ax.set_title(title, fontsize=22, fontweight='bold')

    # 7. [핵심] 우측 범례(Legend) 생성
    # 범례에 "이름 : 00.0%" 형태로 표시
    total = data.sum()
    legend_labels = [f'{label} : {val/total*100:.1f}%' for label, val in zip(data.index, data)]

    ax.legend(
        wedges,
        legend_labels,
        title="플랫폼 비율",
        loc="center left",
        bbox_to_anchor=(0.9, 0.5), # 그래프 오른쪽 바깥에 배치
        fontsize=18
    )

# ------------------------------------------------------------------
# [실행] 시각화
# ------------------------------------------------------------------
# 플랫폼별 고유 색상 정의
platform_colors = {
    '네이버블로그': '#2DB400', # Green
    '네이버카페': '#00C73C',   # Light Green
    '디시인사이드': '#3b5a99', # Blue
    '에펨코리아': '#4682B4',   # Steel Blue
    '더쿠': '#D81B60'         # Pink
}

# 캔버스 설정
fig, axes = plt.subplots(1, 2, figsize=(20, 8)) # 가로 길이를 넉넉하게 잡음

# [A] 전체 데이터
counts_total = df_total['Platform'].value_counts()
plot_smart_donut(
    axes[0],
    counts_total,
    f'[A] 전체 데이터\n총 {len(df_total):,} 건',
    platform_colors
)

# [B] 운세 서비스 후기 데이터
counts_pure = df_pure['Platform'].value_counts()
plot_smart_donut(
    axes[1],
    counts_pure,
    f'[B] 운세 서비스 후기 데이터\n총 {len(df_pure):,} 건',
    platform_colors
)

plt.tight_layout()
plt.subplots_adjust(wspace=0.3) # 두 그래프 사이 간격 조정
plt.show()

"""### 그림 7 각 플랫폼별 게시물에서 언급된 운세 서비스 유형 분포"""

# ==============================================================================
# [Step 1] 데이터 로드 및 준비
# ==============================================================================
# 운세 서비스 후기 데이터 로드
file_path = 'filtered_reviews_data_v26_cleansed.csv'
df_pure = pd.read_csv(file_path)

# 사이트 칼럼을 Platform으로 복사
if 'Platform' not in df_pure.columns:
    df_pure['Platform'] = df_pure['사이트']

# ==============================================================================
# [Step 2] 분석 대상 채널 지정 (순서 정렬 및 재분류)
# ==============================================================================
display_order = [
    '모바일앱(점신/포스텔러 등)',
    'AI(ChatGPT/챗봇 등)',
    '원격/온라인 상담',
    '상담플랫폼(사주나루/홍카페 등)',
    '포털/금융/생활앱',
    '유튜브/영상',
    '기타어플'
]

# 리스트에 있는 주요 채널만 남기기 (기타/미상 등 자동 필터링)
df_pure = df_pure[df_pure['channel_type'].isin(display_order)]

# '기타' 플랫폼 제외 (필요시 유지)
df_pure = df_pure[df_pure['Platform'] != '기타']

# ★ 수정된 핵심 로직: 네이버카페의 AI/챗봇 데이터(2022.11 이전)를 '기타어플'로 재분류
if '작성날짜' in df_pure.columns:
    # 날짜 계산을 위해 datetime으로 변환 (오류 발생 시 NaT 처리)
    df_pure['date'] = pd.to_datetime(df_pure['작성날짜'], errors='coerce')

    # 재분류할 조건: 네이버카페 + AI/챗봇 + 2022년 11월 1일 미만
    change_condition = (
        (df_pure['Platform'] == '네이버카페') &
        (df_pure['channel_type'] == 'AI(ChatGPT/챗봇 등)') &
        (df_pure['date'] < '2022-11-01')
    )

    changed_count = change_condition.sum()

    # 데이터를 삭제하지 않고 '기타어플'로 채널 타입 변경
    df_pure.loc[change_condition, 'channel_type'] = '기타어플'

    print(f"🔄 네이버카페 AI/챗봇 (2022.11 이전) '기타어플'로 재분류: {changed_count:,}건")

print(f"✅ 최종 시각화 대상 데이터: {len(df_pure):,}건")

# ==============================================================================
# [Step 3] 시각화 (도넛 차트 - 비대칭 GridSpec 적용)
# ==============================================================================
platforms_list = ['디시인사이드', '네이버블로그', '네이버카페', '에펨코리아', '더쿠']

# 범례 이름 매핑 딕셔너리
legend_mapping = {
    '모바일앱(점신/포스텔러 등)': '모바일앱',
    'AI(ChatGPT/챗봇 등)': 'AI/챗봇',
    '원격/온라인 상담': '원격/온라인상담',
    '상담플랫폼(사주나루/홍카페 등)': '전문상담플랫폼',
    '포털/금융/생활앱': '포털/금융/생활앱',
    '유튜브/영상': '유튜브/영상',
    '기타어플': '기타 서비스'
}

fig = plt.figure(figsize=(24, 14), constrained_layout=True)

gs = GridSpec(2, 6, figure=fig, height_ratios=[1.2, 1.0])

# 상단 2개, 하단 3개 축(Axes) 생성
ax1 = fig.add_subplot(gs[0, 0:3])
ax2 = fig.add_subplot(gs[0, 3:6])
ax3 = fig.add_subplot(gs[1, 0:2])
ax4 = fig.add_subplot(gs[1, 2:4])
ax5 = fig.add_subplot(gs[1, 4:6])

axes = [ax1, ax2, ax3, ax4, ax5]

# 색상 팔레트 생성 (지정된 채널의 고유 색상 매핑 - 비율이 섞여도 색상은 유지됨)
palette = sns.color_palette("husl", len(display_order))
color_map = dict(zip(display_order, palette))

# 플랫폼별 차트 그리기
for idx, (ax, platform) in enumerate(zip(axes, platforms_list)):
    # 해당 플랫폼 데이터 추출
    subset = df_pure[df_pure['Platform'] == platform]

    if len(subset) == 0:
        ax.text(0.5, 0.5, '데이터 없음', ha='center', va='center', fontsize=20)
        ax.axis('off')
        continue

    # 상단과 하단 그래프의 폰트 크기 차등 적용
    if idx < 2:  # 상단 그래프
        title_fs = 26
        pct_fs = 19
        leg_title_fs = 19
        leg_fs = 16
    else:        # 하단 그래프
        title_fs = 22
        pct_fs = 16
        leg_title_fs = 16
        leg_fs = 14

    # 채널별 빈도 계산 (비율이 높은 순으로 자동 내림차순 정렬)
    counts = subset['channel_type'].value_counts()
    counts = counts[counts > 0] # 0인 항목 제거

    # 파이 차트 그리기
    wedges, texts, autotexts = ax.pie(
        counts,
        labels=None,
        autopct=lambda p: f'{p:.1f}%' if p > 3 else '',
        startangle=90,
        counterclock=False,
        colors=[color_map.get(x, '#999999') for x in counts.index],
        pctdistance=0.85,
        wedgeprops={'edgecolor': 'white', 'linewidth': 1}
    )

    # 도넛 모양 만들기 (가운데 흰색 원 추가)
    centre_circle = plt.Circle((0,0), 0.60, fc='white')
    ax.add_artist(centre_circle)

    # 제목
    ax.set_title(f'[{platform}]\n(n={len(subset):,})', fontsize=title_fs, fontweight='bold')

    # 비율 텍스트 스타일링
    for t in autotexts:
        t.set_fontsize(pct_fs)
        t.set_color('white')
        t.set_fontweight('bold')

    # 우측 범례 추가 (counts가 높은 순으로 정렬되어 있어 범례도 자연스럽게 높은 순이 됩니다)
    legend_labels = [
        f'{legend_mapping.get(i, i)} ({v/sum(counts)*100:.1f}%)'
        for i, v in zip(counts.index, counts)
    ]

    ax.legend(wedges, legend_labels,
              title="운세 서비스 유형",
              title_fontsize=leg_title_fs,
              loc="center left",
              bbox_to_anchor=(0.95, 0.5),
              fontsize=leg_fs)

plt.show()

# ==============================================================================
# [Step 1] 데이터 로드 및 준비
# ==============================================================================
# 운세 서비스 후기 데이터 로드
file_path = 'filtered_reviews_data_v26_cleansed.csv'
df_pure = pd.read_csv(file_path)

# 사이트 칼럼을 Platform으로 복사
if 'Platform' not in df_pure.columns:
    df_pure['Platform'] = df_pure['사이트']

# ==============================================================================
# [Step 2] 분석 대상 채널 지정 (순서 정렬 및 필터링)
# ==============================================================================
display_order = [
    '모바일앱(점신/포스텔러 등)',
    'AI(ChatGPT/챗봇 등)',
    '원격/온라인 상담',
    '상담플랫폼(사주나루/홍카페 등)',
    '포털/금융/생활앱',
    '유튜브/영상',
    '기타어플'
]

# 리스트에 있는 주요 채널만 남기기 (기타/미상 등 자동 필터링)
df_pure = df_pure[df_pure['channel_type'].isin(display_order)]

# '기타' 플랫폼 제외 (필요시 유지)
df_pure = df_pure[df_pure['Platform'] != '기타']

print(f"✅ 최종 시각화 대상 데이터: {len(df_pure):,}건")

# ==============================================================================
# [Step 3] 시각화 (도넛 차트 - 비대칭 GridSpec 적용)
# ==============================================================================
platforms_list = ['디시인사이드', '네이버블로그', '네이버카페', '에펨코리아', '더쿠']

# 범례 이름 매핑 딕셔너리
legend_mapping = {
    '모바일앱(점신/포스텔러 등)': '모바일앱',
    'AI(ChatGPT/챗봇 등)': 'AI/챗봇',
    '원격/온라인 상담': '원격/온라인상담',
    '상담플랫폼(사주나루/홍카페 등)': '전문상담플랫폼',
    '포털/금융/생활앱': '포털/금융/생활앱',
    '유튜브/영상': '유튜브/영상',
    '기타어플': '기타 서비스'
}

fig = plt.figure(figsize=(24, 14), constrained_layout=True)

gs = GridSpec(2, 6, figure=fig, height_ratios=[1.2, 1.0])

# 상단 2개, 하단 3개 축(Axes) 생성
ax1 = fig.add_subplot(gs[0, 0:3])
ax2 = fig.add_subplot(gs[0, 3:6])
ax3 = fig.add_subplot(gs[1, 0:2])
ax4 = fig.add_subplot(gs[1, 2:4])
ax5 = fig.add_subplot(gs[1, 4:6])

axes = [ax1, ax2, ax3, ax4, ax5]

# 색상 팔레트 생성 (지정된 채널의 고유 색상 매핑 - 비율이 섞여도 색상은 유지됨)
palette = sns.color_palette("husl", len(display_order))
color_map = dict(zip(display_order, palette))

# 플랫폼별 차트 그리기
for idx, (ax, platform) in enumerate(zip(axes, platforms_list)):
    # 해당 플랫폼 데이터 추출
    subset = df_pure[df_pure['Platform'] == platform]

    if len(subset) == 0:
        ax.text(0.5, 0.5, '데이터 없음', ha='center', va='center', fontsize=20)
        ax.axis('off')
        continue

    # 상단과 하단 그래프의 폰트 크기 차등 적용
    if idx < 2:  # 상단 그래프
        title_fs = 26
        pct_fs = 19
        leg_title_fs = 19
        leg_fs = 16
    else:        # 하단 그래프
        title_fs = 22
        pct_fs = 16
        leg_title_fs = 16
        leg_fs = 14

    # ★ 핵심 변경: 채널별 빈도 계산 (비율이 높은 순으로 자동 내림차순 정렬)
    counts = subset['channel_type'].value_counts()
    counts = counts[counts > 0] # 0인 항목 제거

    # 파이 차트 그리기
    wedges, texts, autotexts = ax.pie(
        counts,
        labels=None,
        autopct=lambda p: f'{p:.1f}%' if p > 3 else '',
        startangle=90,
        counterclock=False,
        colors=[color_map.get(x, '#999999') for x in counts.index],
        pctdistance=0.85,
        wedgeprops={'edgecolor': 'white', 'linewidth': 1}
    )

    # 도넛 모양 만들기 (가운데 흰색 원 추가)
    centre_circle = plt.Circle((0,0), 0.60, fc='white')
    ax.add_artist(centre_circle)

    # 제목
    ax.set_title(f'[{platform}]\n(n={len(subset):,})', fontsize=title_fs, fontweight='bold')

    # 비율 텍스트 스타일링
    for t in autotexts:
        t.set_fontsize(pct_fs)
        t.set_color('white')
        t.set_fontweight('bold')

    # 우측 범례 추가 (counts가 높은 순으로 정렬되어 있어 범례도 자연스럽게 높은 순이 됩니다)
    legend_labels = [
        f'{legend_mapping.get(i, i)} ({v/sum(counts)*100:.1f}%)'
        for i, v in zip(counts.index, counts)
    ]

    ax.legend(wedges, legend_labels,
              title="운세 서비스 유형",
              title_fontsize=leg_title_fs,
              loc="center left",
              bbox_to_anchor=(0.95, 0.5),
              fontsize=leg_fs)

plt.show()

"""### 그림 8 각 플랫폼 게시물에 언급된 운세 서비스 분포"""

# ==============================================================================
# [Step 1] 데이터 로드 (운세 서비스 후기 데이터)
# ==============================================================================
file_path = 'filtered_reviews_data_v26_cleansed.csv'
df_pure = pd.read_csv(file_path)

# 결측치 방지 및 문자열 변환
df_pure['whole_content'] = df_pure['whole_content'].fillna('').astype(str)

# 사이트 칼럼을 Platform으로 복사 (이미 정리된 상태)
if 'Platform' not in df_pure.columns:
    df_pure['Platform'] = df_pure['사이트']

print(f"📂 분석 대상 순수 후기 데이터 로드: {len(df_pure):,}건")

# ==============================================================================
# [Step 2] 브랜드 키워드 매핑 및 추출
# ==============================================================================
# 브랜드 키워드 사전
target_brands = {
    '포스텔러': ['포스텔러'],
    '점신': ['점신'],
    '홍카페': ['홍카페'],
    '사주나루': ['사주나루'],
    '신통': ['신통'],
    '헬로우봇': ['헬로우봇'],
    '천명': ['천명'],
    '만세력': ['만세력'],
    '천을귀인': ['천을귀인'],
    '사주천궁': ['사주천궁'],
    '운세7': ['운세7'],
    '운세담다': ['운세담다'],
    '운세의신': ['운세의 신', '운세의신'],
    '신비의거울': ['신비의 거울', '신비의거울'],
    '네이버엑스퍼트': ['네이버 엑스퍼트', '네이버엑스퍼트'],
    '오늘의운세': ['오늘의 운세', '오늘의운세']
}

def extract_brand(text):
    text = str(text)
    found_brands = []
    for brand_name, keywords in target_brands.items():
        for kw in keywords:
            if kw in text:
                found_brands.append(brand_name)
                break
    if not found_brands:
        return None
    return found_brands[0] # 첫 번째 발견된 브랜드 반환

print(">>> 브랜드 키워드 추출 중...")
df_pure['Brand'] = df_pure['whole_content'].apply(extract_brand)

# 브랜드가 검출된 데이터만 남기기
df_brand = df_pure.dropna(subset=['Brand'])
print(f"✅ 브랜드 언급 데이터 추출 완료: {len(df_brand):,}건")

# ==============================================================================
# [Step 3] 시각화 (플랫폼별 브랜드 점유율 - 비대칭 GridSpec 적용)
# ==============================================================================
# 플랫폼 리스트
platforms_list = ['디시인사이드', '네이버블로그', '네이버카페', '에펨코리아', '더쿠']

fig = plt.figure(figsize=(24, 14), constrained_layout=True)

# GridSpec 설정: 상단 1.2, 하단 1.0 비율로 2행 6열 생성
gs = GridSpec(2, 6, figure=fig, height_ratios=[1.2, 1.0])

# 상단 2개 그래프 (각각 3열씩 넓게 차지)
ax1 = fig.add_subplot(gs[0, 0:3])
ax2 = fig.add_subplot(gs[0, 3:6])

# 하단 3개 그래프 (각각 2열씩 차지)
ax3 = fig.add_subplot(gs[1, 0:2])
ax4 = fig.add_subplot(gs[1, 2:4])
ax5 = fig.add_subplot(gs[1, 4:6])

# 반복문을 돌리기 위해 축을 리스트로 묶음
axes = [ax1, ax2, ax3, ax4, ax5]

# 색상 팔레트 생성 (브랜드 개수에 맞춤, tab20 사용)
unique_brands = list(target_brands.keys())
palette = sns.color_palette("tab20", len(unique_brands))
color_map = dict(zip(unique_brands, palette))

# 플랫폼별 차트 그리기
for idx, (ax, platform) in enumerate(zip(axes, platforms_list)):
    # 해당 플랫폼 데이터 추출
    subset = df_brand[df_brand['Platform'] == platform]

    if len(subset) == 0:
        ax.text(0.5, 0.5, '데이터 없음', ha='center', va='center', fontsize=20)
        ax.axis('off')
        continue

    # 상단과 하단 그래프의 전체적인 폰트 크기를 더 크게 조정
    if idx < 2:  # 상단 그래프
        title_fs = 26
        pct_fs = 19
        leg_title_fs = 19
        leg_fs = 16
    else:        # 하단 그래프
        title_fs = 22
        pct_fs = 16
        leg_title_fs = 16
        leg_fs = 14

    # 브랜드별 빈도 계산
    counts = subset['Brand'].value_counts()

    # 파이 차트 그리기
    wedges, texts, autotexts = ax.pie(
        counts,
        labels=None,
        autopct=lambda p: f'{p:.1f}%' if p > 2 else '', # 2% 미만 숫자 숨김 유지
        startangle=90,
        counterclock=False,
        colors=[color_map.get(x, '#999999') for x in counts.index],
        pctdistance=0.85,
        wedgeprops={'edgecolor': 'white', 'linewidth': 1}
    )

    # 도넛 모양 만들기
    centre_circle = plt.Circle((0,0), 0.60, fc='white')
    ax.add_artist(centre_circle)

    # 차등 적용된 제목 폰트 크기
    ax.set_title(f'[{platform}]\n(n={len(subset):,})', fontsize=title_fs, fontweight='bold')

    # 차등 적용된 비율 숫자 폰트 크기
    for t in autotexts:
        t.set_fontsize(pct_fs)
        t.set_color('white')
        t.set_fontweight('bold')

    # 우측 범례 추가
    legend_labels = [f'{i} ({v/sum(counts)*100:.1f}%)' for i, v in zip(counts.index, counts)]

    # 차등 적용된 범례 폰트 크기 및 밀착 배치
    ax.legend(wedges, legend_labels,
              title="서비스/브랜드명",
              title_fontsize=leg_title_fs,
              loc="center left",
              bbox_to_anchor=(0.95, 0.5),
              fontsize=leg_fs)

plt.show()

"""### 그림 9 각 플랫폼 운세 서비스 후기형 게시물의 경험 반응 다차원 분석 히트맵"""

plt.rcParams['figure.dpi'] = 100

# ==============================================================================
# [Step 1] 데이터 로드 (운세 서비스 후기 데이터) 및 재분류
# ==============================================================================
file_path = 'filtered_reviews_data_v26_cleansed.csv'
df_pure = pd.read_csv(file_path)

# 결측치 처리 및 문자열 변환
df_pure['whole_content'] = df_pure['whole_content'].fillna('').astype(str)

# 사이트 칼럼을 Platform으로 복사
if 'Platform' not in df_pure.columns:
    df_pure['Platform'] = df_pure['사이트']

# ★ 핵심 보완: 네이버카페 AI/챗봇 (2022.11 이전) 데이터를 '기타어플'로 재분류
if '작성날짜' in df_pure.columns:
    # 날짜 계산을 위해 datetime으로 변환 (오류 발생 시 NaT 처리)
    df_pure['date'] = pd.to_datetime(df_pure['작성날짜'], errors='coerce')

    # 재분류할 조건: 네이버카페 + AI/챗봇 + 2022년 11월 1일 미만
    change_condition = (
        (df_pure['Platform'] == '네이버카페') &
        (df_pure['channel_type'] == 'AI(ChatGPT/챗봇 등)') &
        (df_pure['date'] < '2022-11-01')
    )

    changed_count = change_condition.sum()

    # 데이터를 삭제하지 않고 '기타어플'로 채널 타입 변경
    df_pure.loc[change_condition, 'channel_type'] = '기타어플'

    print(f"🔄 네이버카페 AI/챗봇 (2022.11 이전) '기타어플'로 재분류: {changed_count:,}건")

print(f"✅ 분석 대상 운세 서비스 후기 데이터 준비 완료: {len(df_pure):,}건")

# 분석 대상 채널 리스트 (히트맵 Y축 순서 고정용)
pure_channels = [
    '원격/온라인 상담', '상담플랫폼(사주나루/홍카페 등)',
    'AI(ChatGPT/챗봇 등)', '모바일앱(점신/포스텔러 등)',
    '유튜브/영상', '포털/금융/생활앱', '기타어플'
]

# ==============================================================================
# [Step 2] 5차원 경험 반응 키워드 사전 정의
# ==============================================================================
experience_keywords_5dim = {
    '적중/실력': [
        '맞다', '맞음', '맞는', '맞아', '적중', '정확', '소름', '용하', '용한', '잘봄', '잘본',
        '구체적', '디테일', '상세', '추천', '강추', '졸라 잘', '존나 잘', '개잘', '기가 막히',
        '맞춤', '맞췄', '맞추', '맞춘',
        '틀림', '틀리', '못봄', '못본', '개소리', '사기', '구라', '헛소리', '애매',
        '비추', '거르', '걸러', '엉터리', '안맞', '안 맞', '전혀'
    ],
    '위로/공감': [
        '위로', '위안', '힐링', '후련', '따뜻', '용기', '희망', '소망', '안정', '평안',
        '들어주', '공감', '치유', '친절', '다정', '감사', '힘을 얻', '힘을 내', '힘내',
        '싸가지', '화내', '화나', '혼나', '상처', '욕나', '욕하', '욕할',
        '병신', 'ㅄ', 'ㅂㅅ', '씨발', 'ㅅㅂ', '개새'
    ],
    '재미/흥미': [
        '재미', '잼', '존잼', '꿀잼', '심심', '킬링타임', '흥미', '놀이', '장난', '예능',
        '도파민', '신기', '호기심', '심심풀이', '유행', '찍먹', '시험삼아', '드립', '짤', 'ㅋㅋ'
    ],
    '편의/접근성': [
        '편하', '편해', '쉽다', '쉽게', '쉬움', '빠르', '바로', '간편', '단순', '집에서', '누워서',
        '새벽', '밤에', '언제든', '아무때나', '폰으로', '손쉽', '언제나', '편리', '접근성이 좋',
        '복잡', '귀찮', '렉', '오류', '버그', '안됨', '안 됨', '팅김'
    ],
    '가성비/혜택': [
        '저렴', '싸다', '싼', '만원', '천원', '코인', '쿠폰', '포인트', '충전',
        '무료', '유료', '공짜', '이벤트', '가성비', '혜자', '깊콘', '기프티콘',
        '비싸', '비쌈', '비싼', '창렬', '아깝', '낭비', '돈버림', '돈날', '환불', '흑우', '호구'
    ]
}

# ==============================================================================
# [Step 3] 채널명 변경 매핑 및 분석 함수
# ==============================================================================
legend_mapping = {
    '모바일앱(점신/포스텔러 등)': '모바일앱',
    'AI(ChatGPT/챗봇 등)': 'AI/챗봇',
    '원격/온라인 상담': '원격/온라인상담',
    '상담플랫폼(사주나루/홍카페 등)': '전문상담플랫폼',
    '포털/금융/생활앱': '포털/금융/생활앱',
    '유튜브/영상': '유튜브/영상',
    '기타어플': '기타 서비스'
}

def analyze_emotion_distribution(dataframe, channels, keywords_dict):
    results = []
    for channel in channels:
        subset = dataframe[dataframe['channel_type'] == channel]
        text_blob = ' '.join(subset['whole_content'].tolist())
        total_length = len(text_blob)

        display_name = legend_mapping.get(channel, channel)

        # 데이터가 없을 경우 0으로 채움
        if total_length == 0:
            row = {'Channel': display_name}
            for k in keywords_dict.keys(): row[k] = 0
            results.append(row)
            continue

        row = {'Channel': display_name}
        for category, words in keywords_dict.items():
            count = sum(text_blob.count(w) for w in words)
            # 텍스트 길이에 대비한 출현 빈도 (정규화 스코어)
            normalized_score = (count / total_length) * 10000
            row[category] = normalized_score

        results.append(row)

    return pd.DataFrame(results).set_index('Channel')

# ==============================================================================
# [Step 4] 플랫폼별 히트맵 시각화 (논문용 세팅)
# ==============================================================================
platforms_list = ['디시인사이드', '네이버블로그', None, '네이버카페', '에펨코리아', '더쿠']
cols = 3
rows = math.ceil(len(platforms_list) / cols)

# 서브플롯 간 간격을 위해 figsize 조정
fig, axes = plt.subplots(rows, cols, figsize=(27, 9 * rows))
axes = axes.flatten()

for idx, platform in enumerate(platforms_list):
    ax = axes[idx]

    if platform is None:
        ax.axis('off')
        continue

    df_platform = df_pure[df_pure['Platform'] == platform]
    res_platform = analyze_emotion_distribution(df_platform, pure_channels, experience_keywords_5dim)

    # 히트맵 그리기
    sns.heatmap(
        res_platform,
        annot=True,
        fmt='.1f',
        cmap='Blues',
        linewidths=1.5,           # 셀 간격 선 두께 증가
        linecolor='white',        # 셀 간격 선 색상을 흰색으로 하여 또렷하게 구분
        annot_kws={"size": 14, "weight": "bold"}, # 내부 숫자 크기 키우고 볼드 처리
        cbar_kws={'shrink': 0.8}, # 컬러바 크기 약간 줄여서 깔끔하게 배치
        ax=ax
    )

    # 타이틀 및 축 라벨 폰트 크기 증대
    ax.set_title(f'[{platform}]\n(n={len(df_platform):,})', fontsize=22, fontweight='bold', pad=20)
    ax.set_ylabel('')

    # x축, y축 라벨 크기 증대 및 볼드 처리
    ax.tick_params(axis='x', labelsize=15)
    ax.tick_params(axis='y', labelsize=16, rotation=0)

    for label in ax.get_xticklabels():
        label.set_weight('bold')
    for label in ax.get_yticklabels():
        label.set_weight('bold')

# 남은 빈 서브플롯 제거
for j in range(len(platforms_list), len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

"""### 그림 13 플랫폼별 운세 후기 게시물에서 언급된 AI 모델 분포"""

# ==============================================================================
# [Step 1] 데이터 로드 및 기간 필터링
# ==============================================================================
# 1. 전체 데이터 로드
file_path = 'filtered_reviews_data_v26_cleansed.csv'
df_total = pd.read_csv(file_path)

# 결측치 방지 및 문자열 변환
df_total['whole_content'] = df_total['whole_content'].fillna('').astype(str)

# 2. 사이트 칼럼을 Platform으로 복사
if 'Platform' not in df_total.columns:
    df_total['Platform'] = df_total['사이트']

# 3. 날짜 필터링
df_total['date'] = pd.to_datetime(df_total['작성날짜'], errors='coerce')
df_total = df_total[df_total['date'] >= '2022-11-01']

# ==============================================================================
# [Step 2] AI 서비스 키워드 매핑
# ==============================================================================
# (참고: 소문자로 변환해서 검사하므로 'GPT', 'Gpt' 같은 중복은 제거해도 무방합니다)
target_ai_keywords = {
    'GPT': ['gpt', '지피티', '챗지피티', 'chatgpt'],
    '뤼튼': ['뤼튼', 'wrtn'],
    'Claude': ['claude', '클로드'],
    'Gemini': ['gemini', '제미나이', '재미나이'],
    'Grok': ['grok', '그록'],
    '기타': ['ai 사주', 'ai사주', 'ai운세', 'ai 운세', 'ai타로', 'ai 타로', 'ai 신점', 'ai신점']
}

def extract_ai_keyword(text):
    text_lower = str(text).lower()
    found_ais = []

    for ai_name, keywords in target_ai_keywords.items():
        for kw in keywords:
            if kw == 'ai':
                # 'email', 'again' 등 영문 단어 안의 ai는 제외하고, 순수 ai(또는 한글이 붙은 ai)만 매칭
                if re.search(r'(?<![a-z])ai(?![a-z])', text_lower):
                    found_ais.append(ai_name)
                    break
            else:
                if kw.lower() in text_lower:
                    found_ais.append(ai_name)
                    break

    if not found_ais:
        return None

    # 여러 개가 검출되면 사전에 정의된 순서(GPT > 뤼튼 > ...)대로 가장 첫 번째를 반환
    return found_ais[0]

print(">>> AI 키워드 추출 중...")
df_total['AI_Service'] = df_total['whole_content'].apply(extract_ai_keyword)

# 키워드가 검출된 데이터만 남기기
df_ai_total = df_total.dropna(subset=['AI_Service']).copy()
print(f"✅ AI 키워드 언급 데이터 추출 완료: {len(df_ai_total):,}건")

# ==============================================================================
# [Step 3] 시각화 (플랫폼별 AI 점유율 - 비대칭 GridSpec 적용 및 폰트 확대)
# ==============================================================================
# 플랫폼 리스트
platforms_list = ['디시인사이드', '네이버블로그', '네이버카페', '에펨코리아', '더쿠']

# 전체 캔버스 설정
fig = plt.figure(figsize=(24, 14), constrained_layout=True)

# GridSpec 설정: 상단 1.2, 하단 1.0 비율로 2행 6열 생성
gs = GridSpec(2, 6, figure=fig, height_ratios=[1.2, 1.0])

# 상단 2개 그래프 (각각 3열씩 넓게 차지)
ax1 = fig.add_subplot(gs[0, 0:3])
ax2 = fig.add_subplot(gs[0, 3:6])

# 하단 3개 그래프 (각각 2열씩 차지)
ax3 = fig.add_subplot(gs[1, 0:2])
ax4 = fig.add_subplot(gs[1, 2:4])
ax5 = fig.add_subplot(gs[1, 4:6])

axes = [ax1, ax2, ax3, ax4, ax5]

# 색상 팔레트 생성 ('기타'는 회색으로 고정)
unique_ais = list(target_ai_keywords.keys())
palette = sns.color_palette("Paired", len(unique_ais))
color_map = dict(zip(unique_ais, palette))
color_map['기타'] = '#C0C0C0' # 회색 지정

# 플랫폼별 시각화
for idx, (ax, platform) in enumerate(zip(axes, platforms_list)):
    subset = df_ai_total[df_ai_total['Platform'] == platform]

    if len(subset) == 0:
        ax.text(0.5, 0.5, '데이터 없음', ha='center', va='center', fontsize=20)
        ax.axis('off')
        continue

    # 상단과 하단 그래프의 전체적인 폰트 크기를 차등 적용
    if idx < 2:  # 상단 그래프
        title_fs = 26
        pct_fs = 19
        leg_title_fs = 19
        leg_fs = 16
    else:        # 하단 그래프
        title_fs = 22
        pct_fs = 16
        leg_title_fs = 16
        leg_fs = 14

    # AI별 빈도 계산
    counts = subset['AI_Service'].value_counts()

    # ★ '기타'를 강제로 맨 끝으로 이동시키는 로직
    target_others = '기타'
    if target_others in counts.index:
        others_val = counts[target_others]
        counts = counts.drop(target_others)
        counts[target_others] = others_val

    # 파이 차트 그리기
    wedges, texts, autotexts = ax.pie(
        counts,
        labels=None,
        autopct=lambda p: f'{p:.1f}%' if p > 2 else '', # 2% 미만 숫자 숨김
        startangle=90,
        counterclock=False,
        colors=[color_map.get(x, '#999999') for x in counts.index],
        pctdistance=0.85,
        wedgeprops={'edgecolor': 'white', 'linewidth': 1}
    )

    # 도넛 모양 만들기 (가운데 흰색 원 추가)
    centre_circle = plt.Circle((0,0), 0.60, fc='white')
    ax.add_artist(centre_circle)

    # 타이틀
    ax.set_title(f'[{platform}]\n(n={len(subset):,})', fontsize=title_fs, fontweight='bold')

    # 비율 텍스트 폰트 설정
    for t in autotexts:
        t.set_fontsize(pct_fs)
        t.set_color('white')
        t.set_fontweight('bold')

    # 우측 범례 추가
    legend_labels = [f'{i} ({v/sum(counts)*100:.1f}%)' for i, v in zip(counts.index, counts)]

    ax.legend(wedges, legend_labels,
              title="AI 모델",
              title_fontsize=leg_title_fs,
              loc="center left",
              bbox_to_anchor=(0.95, 0.5),
              fontsize=leg_fs)

plt.show()

"""### 그림 14 플랫폼별 전체 게시물에서 언급된 AI 모델 분포"""

# ==============================================================================
# [Step 1] 데이터 로드 및 기간 필터링
# ==============================================================================
# 1. 전체 데이터 로드
file_path = 'tagged_result_final_v26_cleansed.csv'
df_total = pd.read_csv(file_path)

# 결측치 방지 및 문자열 변환
df_total['whole_content'] = df_total['whole_content'].fillna('').astype(str)

# 2. 사이트 칼럼을 Platform으로 복사
if 'Platform' not in df_total.columns:
    df_total['Platform'] = df_total['사이트']

# 3. 날짜 필터링
df_total['date'] = pd.to_datetime(df_total['작성날짜'], errors='coerce')
df_total = df_total[df_total['date'] >= '2022-11-01']

# ==============================================================================
# [Step 2] AI 서비스 키워드 매핑
# ==============================================================================
# (참고: 소문자로 변환해서 검사하므로 'GPT', 'Gpt' 같은 중복은 제거해도 무방합니다)
target_ai_keywords = {
    'GPT': ['gpt', '지피티', '챗지피티', 'chatgpt'],
    '뤼튼': ['뤼튼', 'wrtn'],
    'Claude': ['claude', '클로드'],
    'Gemini': ['gemini', '제미나이', '재미나이'],
    'Grok': ['grok', '그록'],
    '기타': ['ai 사주', 'ai사주', 'ai운세', 'ai 운세', 'ai타로', 'ai 타로', 'ai 신점', 'ai신점']
}


def extract_ai_keyword(text):
    text_lower = str(text).lower()
    found_ais = []

    for ai_name, keywords in target_ai_keywords.items():
        for kw in keywords:
            if kw == 'ai':
                # 'email', 'again' 등 영문 단어 안의 ai는 제외하고, 순수 ai(또는 한글이 붙은 ai)만 매칭
                if re.search(r'(?<![a-z])ai(?![a-z])', text_lower):
                    found_ais.append(ai_name)
                    break
            else:
                if kw.lower() in text_lower:
                    found_ais.append(ai_name)
                    break

    if not found_ais:
        return None

    # 여러 개가 검출되면 사전에 정의된 순서(GPT > 뤼튼 > ...)대로 가장 첫 번째를 반환
    return found_ais[0]

print(">>> AI 키워드 추출 중...")
df_total['AI_Service'] = df_total['whole_content'].apply(extract_ai_keyword)

# 키워드가 검출된 데이터만 남기기
df_ai_total = df_total.dropna(subset=['AI_Service']).copy()
print(f"✅ AI 키워드 언급 데이터 추출 완료: {len(df_ai_total):,}건")

# ==============================================================================
# [Step 3] 시각화 (플랫폼별 AI 점유율 - 비대칭 GridSpec 적용 및 폰트 확대)
# ==============================================================================
# 플랫폼 리스트
platforms_list = ['디시인사이드', '네이버블로그', '네이버카페', '에펨코리아', '더쿠']

# 전체 캔버스 설정
fig = plt.figure(figsize=(24, 14), constrained_layout=True)

# GridSpec 설정: 상단 1.2, 하단 1.0 비율로 2행 6열 생성
gs = GridSpec(2, 6, figure=fig, height_ratios=[1.2, 1.0])

# 상단 2개 그래프 (각각 3열씩 넓게 차지)
ax1 = fig.add_subplot(gs[0, 0:3])
ax2 = fig.add_subplot(gs[0, 3:6])

# 하단 3개 그래프 (각각 2열씩 차지)
ax3 = fig.add_subplot(gs[1, 0:2])
ax4 = fig.add_subplot(gs[1, 2:4])
ax5 = fig.add_subplot(gs[1, 4:6])

axes = [ax1, ax2, ax3, ax4, ax5]

# 색상 팔레트 생성 ('기타'는 회색으로 고정)
unique_ais = list(target_ai_keywords.keys())
palette = sns.color_palette("Paired", len(unique_ais))
color_map = dict(zip(unique_ais, palette))
color_map['기타'] = '#C0C0C0' # 회색 지정

# 플랫폼별 시각화
for idx, (ax, platform) in enumerate(zip(axes, platforms_list)):
    subset = df_ai_total[df_ai_total['Platform'] == platform]

    if len(subset) == 0:
        ax.text(0.5, 0.5, '데이터 없음', ha='center', va='center', fontsize=20)
        ax.axis('off')
        continue

    # 상단과 하단 그래프의 전체적인 폰트 크기를 차등 적용
    if idx < 2:  # 상단 그래프
        title_fs = 26
        pct_fs = 19
        leg_title_fs = 19
        leg_fs = 16
    else:        # 하단 그래프
        title_fs = 22
        pct_fs = 16
        leg_title_fs = 16
        leg_fs = 14

    # AI별 빈도 계산
    counts = subset['AI_Service'].value_counts()

    # ★ '기타'를 강제로 맨 끝으로 이동시키는 로직
    target_others = '기타'
    if target_others in counts.index:
        others_val = counts[target_others]
        counts = counts.drop(target_others)
        counts[target_others] = others_val

    # 파이 차트 그리기
    wedges, texts, autotexts = ax.pie(
        counts,
        labels=None,
        autopct=lambda p: f'{p:.1f}%' if p > 2 else '', # 2% 미만 숫자 숨김
        startangle=90,
        counterclock=False,
        colors=[color_map.get(x, '#999999') for x in counts.index],
        pctdistance=0.85,
        wedgeprops={'edgecolor': 'white', 'linewidth': 1}
    )

    # 도넛 모양 만들기 (가운데 흰색 원 추가)
    centre_circle = plt.Circle((0,0), 0.60, fc='white')
    ax.add_artist(centre_circle)

    # 타이틀
    ax.set_title(f'[{platform}]\n(n={len(subset):,})', fontsize=title_fs, fontweight='bold')

    # 비율 텍스트 폰트 설정
    for t in autotexts:
        t.set_fontsize(pct_fs)
        t.set_color('white')
        t.set_fontweight('bold')

    # 우측 범례 추가
    legend_labels = [f'{i} ({v/sum(counts)*100:.1f}%)' for i, v in zip(counts.index, counts)]

    ax.legend(wedges, legend_labels,
              title="AI 모델",
              title_fontsize=leg_title_fs,
              loc="center left",
              bbox_to_anchor=(0.95, 0.5),
              fontsize=leg_fs)

plt.show()