# -*- coding: utf-8 -*-
"""temporal_trends

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GguMhQhcHCZ5fdVqY0POhwUQywuqGk7j

# 시계열 분석
"""

# [0] 폰트 및 라이브러리 설정
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import make_interp_spline
import math

plt.rc('font', family='NanumBarunGothic')
plt.rcParams['axes.unicode_minus'] = False

"""### 그림 2 플랫폼별 운세 게시물 추이(2019~2025. 09)"""

# ==============================================================================
# [Step 1] 데이터 로드 및 준비
# ==============================================================================
def load_and_prepare_data(file_path):
    df = pd.read_csv(file_path)

    # 1. 날짜 데이터
    df['date'] = pd.to_datetime(df['작성날짜'], errors='coerce')

    # 2. 분기(Quarter) 단위 변환 (트렌드 시각화용)
    df['Period'] = df['date'].dt.to_period('Q')

    # 3. 사이트 칼럼을 Platform으로 복사
    if 'Platform' not in df.columns:
        df['Platform'] = df['사이트']

    return df

# ==============================================================================
# [Step 2] 분기별 데이터 집계
# ==============================================================================
def prepare_platform_trend(df, platforms_order):
    # 플랫폼별/분기별 게시글 수 집계
    quarterly_counts = df.groupby(['Platform', 'Period']).size().unstack(fill_value=0)

    # 기간 내 모든 분기를 컬럼으로 확보 (2019Q1 ~ 2025Q3)
    start_date = "2019-01-01"
    end_date = "2025-09-30"
    all_quarters = pd.period_range(start=start_date, end=end_date, freq='Q')
    quarterly_counts = quarterly_counts.reindex(columns=all_quarters, fill_value=0)

    # 지정된 플랫폼 순서대로 정렬
    quarterly_counts = quarterly_counts.reindex(platforms_order, fill_value=0)

    return quarterly_counts

# ==============================================================================
# [Step 3] 시각화 함수 (비대칭 2-top, 3-bottom 배치 적용)
# ==============================================================================
from matplotlib.gridspec import GridSpec

def plot_horizontal_trends(data_df, platform_colors, output_path):
    platforms = data_df.index.tolist()

    # 전체 캔버스 설정 (상하 2행 배치를 위해 세로 길이를 대폭 늘림)
    fig = plt.figure(figsize=(24, 14), constrained_layout=True)

    # GridSpec 설정: 상단 1.2, 하단 1.0 비율로 2행 6열 생성
    gs = GridSpec(2, 6, figure=fig, height_ratios=[1.2, 1.0])

    # 상단 2개 그래프 (각각 3열씩 넓게 차지)
    ax1 = fig.add_subplot(gs[0, 0:3])
    ax2 = fig.add_subplot(gs[0, 3:6])

    # 하단 3개 그래프 (각각 2열씩 차지)
    ax3 = fig.add_subplot(gs[1, 0:2])
    ax4 = fig.add_subplot(gs[1, 2:4])
    ax5 = fig.add_subplot(gs[1, 4:6])

    axes = [ax1, ax2, ax3, ax4, ax5]

    for idx, (ax, platform) in enumerate(zip(axes, platforms)):
        color_code = platform_colors.get(platform, '#999999')

        row_data = data_df.iloc[idx].values
        numeric_data = pd.to_numeric(row_data, errors='coerce')
        x = np.arange(len(numeric_data))

        mask = ~np.isnan(numeric_data)
        valid_x = x[mask]
        valid_data = numeric_data[mask]

        # 상단과 하단 그래프의 폰트 크기를 다르게 설정
        if idx < 2:  # 상단 그래프
            title_fs = 31      # 하단 플랫폼 이름 폰트
            anno_fs = 24       # 최고/최저점 숫자 폰트
            tick_fs = 21       # X축 연도 폰트
            line_w = 5         # 상단은 선 굵기도 살짝 두껍게
        else:        # 하단 그래프
            title_fs = 25
            anno_fs = 20
            tick_fs = 19
            line_w = 4

        # 스플라인 곡선 (부드럽게 표현)
        if len(valid_data) > 3:
            try:
                x_smooth = np.linspace(valid_x.min(), valid_x.max(), 300)
                spl = make_interp_spline(valid_x, valid_data, k=3)
                y_smooth = np.clip(spl(x_smooth), 0, None)
                ax.fill_between(x_smooth, y_smooth, 0, color=color_code, alpha=0.2)
                ax.plot(x_smooth, y_smooth, color=color_code, linewidth=line_w)
            except:
                ax.fill_between(valid_x, valid_data, 0, color=color_code, alpha=0.2)
                ax.plot(valid_x, valid_data, color=color_code, linewidth=line_w)
        else:
            ax.fill_between(valid_x, valid_data, 0, color=color_code, alpha=0.2)
            ax.plot(valid_x, valid_data, color=color_code, linewidth=line_w)

        # 최고/최저값 텍스트 표시
        if len(valid_data) > 0:
            max_idx = np.argmax(valid_data)
            min_idx = np.argmin(valid_data)
            max_val = valid_data[max_idx]
            min_val = valid_data[min_idx]
            max_x_pos = valid_x[max_idx]
            min_x_pos = valid_x[min_idx]

            disp_max = f"{int(max_val):,}"
            disp_min = f"{int(min_val):,}"

            ax.annotate(disp_max, (max_x_pos, max_val),
                        textcoords="offset points", xytext=(0, 10),
                        ha='center', fontsize=anno_fs, fontweight='bold', color=color_code)

            ax.annotate(disp_min, (min_x_pos, min_val),
                        textcoords="offset points", xytext=(0, -15),
                        ha='center', fontsize=anno_fs, fontweight='bold', color=color_code)

        # 플랫폼 이름 (하단 중앙) - 다단 배치 시 겹치지 않도록 위치 미세 조정 (-0.15)
        ax.text(0.5, -0.15, platform, transform=ax.transAxes,
                ha='center', va='top', fontsize=title_fs, fontweight='bold')

        # X축 눈금 (2019 ~ 2025)
        years = ['19', '20', '21', '22', '23', '24', '25']
        ticks = [i*4 for i in range(len(years))]
        valid_ticks = [t for t in ticks if t < len(numeric_data)]
        valid_labels = [years[i] for i, t in enumerate(ticks) if t < len(numeric_data)]

        ax.set_xticks(valid_ticks)
        ax.set_xticklabels(valid_labels, fontsize=tick_fs, color='gray')

        # Y축 범위 여유있게 (텍스트가 잘리지 않도록 1.35로 살짝 상향)
        if len(valid_data) > 0:
            y_max = np.nanmax(valid_data)
            ax.set_ylim(0, y_max * 1.35)

        # 디자인 정리 (Spine 제거)
        for spine in ax.spines.values():
            spine.set_visible(False)
        ax.tick_params(axis='x', length=0, pad=10)
        ax.set_yticks([])
        ax.set_xlim(-1, 28)

    # constrained_layout을 사용하므로 tight_layout()은 제외됨
    plt.savefig(output_path, dpi=300, bbox_inches='tight', facecolor='white')
    print(f"✅ 이미지 저장 완료: {output_path}")
    plt.show()

# ==============================================================================
# [실행부]
# ==============================================================================
# 운세 서비스 후기 데이터
file_path = 'filtered_reviews_data_v26_cleansed.csv'

# 1. 데이터 로드 및 준비 (분기 변환)
df_pure = load_and_prepare_data(file_path)
print(f"📂 분석 대상 운세 서비스 후기 데이터: {len(df_pure):,}건")

# 2. 플랫폼 순서 및 색상
platforms_order = ['네이버블로그', '디시인사이드', '네이버카페', '에펨코리아', '더쿠']
platforms_colors = {
    '네이버블로그': '#2DB400',
    '디시인사이드': '#3b5a99',
    '네이버카페': '#00C73C',
    '에펨코리아': '#4682B4',
    '더쿠': '#D81B60'
}

# 3. 데이터 집계 (분기별 묶기)
trend_data = prepare_platform_trend(df_pure, platforms_order)

# 4. 시각화
plot_horizontal_trends(trend_data, platforms_colors, 'platform_pure_trend_horizontal.png')

"""### 그림3-6 운세 서비스 유형별 언급 게시물 수 추이"""

# ==============================================================================
# [Step 1] 데이터 로드 및 준비 (분기 변환 및 채널 재분류)
# ==============================================================================
def load_and_prepare(file_path):
    df = pd.read_csv(file_path)

    # 1. 날짜 데이터 (필터링 생략)
    df['date'] = pd.to_datetime(df['작성날짜'], errors='coerce')

    # 2. 분기(Quarter) 단위 변환
    df['Period'] = df['date'].dt.to_period('Q')

    # 3. 사이트 칼럼을 Platform으로 복사
    if 'Platform' not in df.columns:
        df['Platform'] = df['사이트']

    # ★ 핵심 보완: 네이버카페 AI/챗봇 (2022.11 이전) 데이터를 '기타어플'로 재분류
    change_condition = (
        (df['Platform'] == '네이버카페') &
        (df['channel_type'] == 'AI(ChatGPT/챗봇 등)') &
        (df['date'] < '2022-11-01')
    )

    changed_count = change_condition.sum()
    df.loc[change_condition, 'channel_type'] = '기타어플'

    print(f"🔄 네이버카페 AI/챗봇 (2022.11 이전) '기타어플'로 재분류: {changed_count:,}건")

    # X축(분기) 고정을 위한 시작/종료일 설정
    start_date = "2019-01-01"
    end_date = "2025-09-30"

    return df, start_date, end_date

# ==============================================================================
# [Step 2] 분기별 집계 데이터 변환 (지정된 순서 유지)
# ==============================================================================
def prepare_quarterly_data(df_platform, column_name, start_date, end_date, target_list):
    # 1. 먼저 대상 항목으로만 데이터 필터링 (레이아웃 순서 유지용)
    df_filtered = df_platform[df_platform[column_name].isin(target_list)]

    # 2. 분기별/항목별 집계
    quarterly_counts = df_filtered.groupby([column_name, 'Period']).size().unstack(fill_value=0)

    # 3. 기간 내 모든 분기를 컬럼으로 확보 (빈 분기는 0 채우기)
    all_quarters = pd.period_range(start=start_date, end=end_date, freq='Q')
    quarterly_counts = quarterly_counts.reindex(columns=all_quarters, fill_value=0)

    # 4. 행(Index)을 target_list 순서대로 고정 (데이터가 없어도 패널 유지를 위해 0으로 추가)
    final_df = quarterly_counts.reindex(target_list, fill_value=0)

    return final_df

# ==============================================================================
# [Step 3] 시각화 함수
# ==============================================================================
def plot_service_grid(data_df, output_path, main_title="", color_code='#71b27f'):

    LINE_COLOR = color_code
    POINT_COLOR = color_code
    FILL_COLOR = color_code

    services = data_df.index.tolist()
    num_plots = len(services)

    if num_plots == 0:
        return

    # 행/열 계산 (3열 고정)
    cols = 3
    rows = math.ceil(num_plots / cols)

    fig, axes = plt.subplots(rows, cols, figsize=(15, 4 * rows), facecolor='white')

    # 제목이 있을 때만 표시
    if main_title:
        fig.suptitle(main_title, fontsize=30, fontweight='bold', y=1.00 + (0.02/rows))

    if num_plots > 1:
        axes = axes.flatten()
    else:
        axes = [axes]

    for idx, ax in enumerate(axes):
        if idx < num_plots:
            service = services[idx]
            row_data = data_df.iloc[idx].values
            numeric_data = pd.to_numeric(row_data, errors='coerce')
            x = np.arange(len(numeric_data))

            mask = ~np.isnan(numeric_data)
            valid_x = x[mask]
            valid_data = numeric_data[mask]

            # 스플라인 곡선 (부드럽게)
            if len(valid_data) > 3 and valid_data.max() > 0: # 데이터가 모두 0인 경우 스플라인 오류 방지
                try:
                    x_smooth = np.linspace(valid_x.min(), valid_x.max(), 300)
                    spl = make_interp_spline(valid_x, valid_data, k=3)
                    y_smooth = np.clip(spl(x_smooth), 0, None)
                    ax.fill_between(x_smooth, y_smooth, 0, color=FILL_COLOR, alpha=0.2)
                    ax.plot(x_smooth, y_smooth, color=LINE_COLOR, linewidth=3)
                except:
                    ax.fill_between(valid_x, valid_data, 0, color=FILL_COLOR, alpha=0.2)
                    ax.plot(valid_x, valid_data, color=LINE_COLOR, linewidth=3)
            else:
                ax.fill_between(valid_x, valid_data, 0, color=FILL_COLOR, alpha=0.2)
                ax.plot(valid_x, valid_data, color=LINE_COLOR, linewidth=3)

            # 최고/최저값 텍스트 표시 (값이 0보다 클 때만 표시)
            if len(valid_data) > 0 and valid_data.max() > 0:
                max_idx = np.argmax(valid_data)
                min_idx = np.argmin(valid_data)
                max_val = valid_data[max_idx]
                min_val = valid_data[min_idx]
                max_x_pos = valid_x[max_idx]
                min_x_pos = valid_x[min_idx]

                disp_max = f"{int(max_val):,}"
                disp_min = f"{int(min_val):,}"

                ax.annotate(disp_max, (max_x_pos, max_val),
                            textcoords="offset points", xytext=(0, 8),
                            ha='center', fontsize=16, fontweight='bold', color=POINT_COLOR)

                ax.annotate(disp_min, (min_x_pos, min_val),
                            textcoords="offset points", xytext=(0, -12),
                            ha='center', fontsize=16, fontweight='bold', color=POINT_COLOR)

            # 서비스명 타이틀
            ax.text(0.5, -0.2, service, transform=ax.transAxes,
                    ha='center', va='top', fontsize=20, fontweight='bold')

            # X축 눈금 (2019 ~ 2025)
            years = ['19', '20', '21', '22', '23', '24', '25']
            ticks = [i*4 for i in range(len(years))]
            valid_ticks = [t for t in ticks if t < len(numeric_data)]
            valid_labels = [years[i] for i, t in enumerate(ticks) if t < len(numeric_data)]

            ax.set_xticks(valid_ticks)
            ax.set_xticklabels(valid_labels, fontsize=14, color='gray')

            if len(valid_data) > 0 and valid_data.max() > 0:
                y_max = np.nanmax(valid_data)
                ax.set_ylim(0, y_max * 1.3)
            else:
                ax.set_ylim(0, 10) # 데이터가 0일 경우 기본 y축 설정
        else:
            ax.axis('off')

        for spine in ax.spines.values():
            spine.set_visible(False)
        ax.tick_params(axis='x', length=0, pad=10)
        ax.set_yticks([])
        ax.set_xlim(-1, 28)

    plt.tight_layout(h_pad=3.0, w_pad=2.0)
    plt.savefig(output_path, dpi=150, bbox_inches='tight', facecolor='white')
    print(f"✅ 이미지 저장 완료: {output_path}")
    plt.show()

# ==============================================================================
# [실행부]
# ==============================================================================
# 운세 서비스 후기 데이터
file_path = 'filtered_reviews_data_v26_cleansed.csv'

# 1. 데이터 로드 (재분류 포함)
df_all, start_date, end_date = load_and_prepare(file_path)
print(f"📂 분석 대상 전체 데이터: {len(df_all):,}건")

# 2. 플랫폼별 색상
platforms_info = {
    '네이버블로그': '#2DB400',
    '디시인사이드': '#3b5a99',
    '네이버카페': '#00C73C',
    '에펨코리아': '#4682B4',
    '더쿠': '#D81B60'
}

# 3. 레이아웃 배치를 위한 채널 순서 정의
valid_channels = [
    '원격/온라인 상담',               # 상단 1
    '상담플랫폼(사주나루/홍카페 등)',    # 상단 2
    '유튜브/영상',                    # 상단 3
    '모바일앱(점신/포스텔러 등)',       # 중단 1
    '포털/금융/생활앱',               # 중단 2
    'AI(ChatGPT/챗봇 등)',            # 중단 3
    '기타어플'                        # 하단 1
]

print("\n>>> 플랫폼별 분기별(Quarterly) 채널 추이 시각화 시작\n")

for platform, color in platforms_info.items():
    print(f"■ Processing: {platform}")

    df_platform = df_all[df_all['Platform'] == platform]
    if len(df_platform) == 0:
        print(f"  - {platform} 데이터가 없어 건너뜁니다.")
        continue

    # (A) 채널 시각화 처리
    try:
        channel_data = prepare_quarterly_data(
            df_platform, 'channel_type', start_date, end_date, valid_channels
        )

        plot_service_grid(
            channel_data,
            f'trend_channel_{platform}_selected.png',
            "", # 전체 제목 제거
            color_code=color
        )
    except Exception as e:
        print(f" - 채널 분석 오류: {e}")

    print("-" * 30)

"""### 그림 12 플랫폼별 AI 키워드 빈도값 추이

##### 전체 데이터
"""

# ==============================================================================
# [Step 1] 데이터 로드 및 전처리 (AI 키워드 추출 및 날짜 필터링)
# ==============================================================================
def load_and_preprocess_ai_data(file_path):
    df = pd.read_csv(file_path)
    df['whole_content'] = df['whole_content'].fillna('').astype(str)

    # 1. 날짜 데이터
    df['date'] = pd.to_datetime(df['작성날짜'], errors='coerce')

    # ★ 2022년 11월 1일 이후 데이터만 남기기
    df = df[df['date'] >= '2022-11-01']
    print(f"✅ 2022년 11월 이후 분석 대상 데이터: {len(df):,}건")

    # 2. 분기(Quarter) 단위 변환
    df['Period'] = df['date'].dt.to_period('Q')

    # 3. 사이트 칼럼을 Platform으로 복사
    if 'Platform' not in df.columns:
        df['Platform'] = df['사이트']

    # '기타' 플랫폼 제외
    df = df[df['Platform'] != '기타']

    # 4. AI 서비스 키워드 추출
    target_ai_keywords = {
        'GPT': ['gpt', 'Gpt', '지피티', 'GPT', '챗지피티', 'chatgpt'],
        '뤼튼': ['뤼튼', 'wrtn'],
        'Claude': ['Claude', '클로드'],
        'Gemini': ['Gemini', '제미나이', '재미나이'],
        'Grok': ['Grok', '그록'],
        '기타': ['ai 사주', 'ai사주', 'ai운세', 'ai 운세', 'ai타로', 'ai 타로', 'ai 신점', 'ai신점']
    }

    def extract_ai_keyword(text):
        text_lower = str(text).lower()
        found_ais = []
        for ai_name, keywords in target_ai_keywords.items():
            for kw in keywords:
                if kw.lower() in text_lower:
                    found_ais.append(ai_name)
                    break
        if not found_ais:
            return None
        return found_ais[0]

    print(">>> AI 키워드 추출 중...")
    df['AI_Service'] = df['whole_content'].apply(extract_ai_keyword)

    # AI 키워드가 언급된 데이터만 필터링
    df_ai = df.dropna(subset=['AI_Service']).copy()
    print(f"✅ AI 키워드 언급 데이터 추출 완료: {len(df_ai):,}건")

    # X축(분기) 고정을 위한 시작/종료일 설정 (22년 11월이 포함된 22년 4분기부터 시작)
    start_date = "2019-01-01"
    end_date = "2025-09-30"

    return df_ai, start_date, end_date

# ==============================================================================
# [Step 2] 분기별/플랫폼별 전체 AI 게시글 수 집계
# ==============================================================================
def prepare_platform_trend(df, start_date, end_date, platforms_order):
    # 플랫폼별/분기별 게시글 수 집계 (AI 서비스 총합)
    quarterly_counts = df.groupby(['Platform', 'Period']).size().unstack(fill_value=0)

    # 기간 내 모든 분기를 컬럼으로 확보
    all_quarters = pd.period_range(start=start_date, end=end_date, freq='Q')
    quarterly_counts = quarterly_counts.reindex(columns=all_quarters, fill_value=0)

    # 지정된 플랫폼 순서대로 정렬 (누락된 플랫폼은 0으로 채움)
    quarterly_counts = quarterly_counts.reindex(platforms_order, fill_value=0)

    return quarterly_counts, all_quarters

# ==============================================================================
# [Step 3] 시각화 함수 (비대칭 2-top, 3-bottom 배치 적용)
# ==============================================================================
def plot_horizontal_trends(data_df, platform_colors, output_path, all_quarters):
    from matplotlib.gridspec import GridSpec

    platforms = data_df.index.tolist()

    # 전체 캔버스 설정
    fig = plt.figure(figsize=(24, 14), constrained_layout=True)

    # GridSpec 설정: 상단 1.2, 하단 1.0 비율로 2행 6열 생성
    gs = GridSpec(2, 6, figure=fig, height_ratios=[1.2, 1.0])

    # 상단 2개 그래프 (각각 3열씩 넓게 차지)
    ax1 = fig.add_subplot(gs[0, 0:3])
    ax2 = fig.add_subplot(gs[0, 3:6])

    # 하단 3개 그래프 (각각 2열씩 차지)
    ax3 = fig.add_subplot(gs[1, 0:2])
    ax4 = fig.add_subplot(gs[1, 2:4])
    ax5 = fig.add_subplot(gs[1, 4:6])

    axes = [ax1, ax2, ax3, ax4, ax5]

    # 동적 X축 라벨 생성 (예: '23 1Q)
    x_labels = [f"'{str(q.year)[2:]} {q.quarter}Q" for q in all_quarters]

    for idx, (ax, platform) in enumerate(zip(axes, platforms)):
        color_code = platform_colors.get(platform, '#999999')

        row_data = data_df.iloc[idx].values
        numeric_data = pd.to_numeric(row_data, errors='coerce')
        x = np.arange(len(numeric_data))

        mask = ~np.isnan(numeric_data)
        valid_x = x[mask]
        valid_data = numeric_data[mask]

        # 상단과 하단 그래프의 폰트 및 선 굵기를 다르게 설정
        if idx < 2:  # 상단 그래프
            title_fs = 26      # 하단 플랫폼 이름(n=) 폰트
            anno_fs = 18       # 최고/최저점 숫자 폰트
            tick_fs = 15       # X축 연도 폰트
            line_w = 4         # 상단은 선 굵기도 살짝 두껍게
        else:        # 하단 그래프
            title_fs = 20
            anno_fs = 14
            tick_fs = 13
            line_w = 3

        # 스플라인 곡선 (부드럽게)
        if len(valid_data) > 3 and valid_data.max() > 0:
            try:
                x_smooth = np.linspace(valid_x.min(), valid_x.max(), 300)
                spl = make_interp_spline(valid_x, valid_data, k=3)
                y_smooth = np.clip(spl(x_smooth), 0, None)
                ax.fill_between(x_smooth, y_smooth, 0, color=color_code, alpha=0.2)
                ax.plot(x_smooth, y_smooth, color=color_code, linewidth=line_w)
            except:
                ax.fill_between(valid_x, valid_data, 0, color=color_code, alpha=0.2)
                ax.plot(valid_x, valid_data, color=color_code, linewidth=line_w)
        else:
            ax.fill_between(valid_x, valid_data, 0, color=color_code, alpha=0.2)
            ax.plot(valid_x, valid_data, color=color_code, linewidth=line_w)

        # 최고/최저값 텍스트 표시
        if len(valid_data) > 0 and valid_data.max() > 0:
            max_idx = np.argmax(valid_data)
            min_idx = np.argmin(valid_data)
            max_val = valid_data[max_idx]
            min_val = valid_data[min_idx]
            max_x_pos = valid_x[max_idx]
            min_x_pos = valid_x[min_idx]

            disp_max = f"{int(max_val):,}"
            disp_min = f"{int(min_val):,}"

            ax.annotate(disp_max, (max_x_pos, max_val),
                        textcoords="offset points", xytext=(0, 10),
                        ha='center', fontsize=anno_fs, fontweight='bold', color=color_code)

            ax.annotate(disp_min, (min_x_pos, min_val),
                        textcoords="offset points", xytext=(0, -15),
                        ha='center', fontsize=anno_fs, fontweight='bold', color=color_code)

        # 플랫폼 이름 (하단 중앙) - 다단 배치 시 겹치지 않도록 위치 미세 조정 (-0.15)
        total_n = int(valid_data.sum()) if len(valid_data) > 0 else 0
        ax.text(0.5, -0.15, f"{platform}\n(n={total_n:,})", transform=ax.transAxes,
                ha='center', va='top', fontsize=title_fs, fontweight='bold')

        # ★ X축 눈금 원복 (2019 ~ 2025, 분기 표기 생략)
        years = ['19', '20', '21', '22', '23', '24', '25']
        ticks = [i*4 for i in range(len(years))]
        valid_ticks = [t for t in ticks if t < len(numeric_data)]
        valid_labels = [years[i] for i, t in enumerate(ticks) if t < len(numeric_data)]

        ax.set_xticks(valid_ticks)
        ax.set_xticklabels(valid_labels, fontsize=tick_fs, color='gray')

        # Y축 범위 여유있게 (텍스트가 잘리지 않도록 1.35로 살짝 상향)
        if len(valid_data) > 0 and valid_data.max() > 0:
            y_max = np.nanmax(valid_data)
            ax.set_ylim(0, y_max * 1.35)
        else:
            ax.set_ylim(0, 10)

        # 디자인 깔끔하게 (Spine 제거)
        for spine in ax.spines.values():
            spine.set_visible(False)
        ax.tick_params(axis='x', length=0, pad=10)
        ax.set_yticks([])

        # X축 좌우 여백 설정 (분기 수에 맞춰 동적 조절)
        ax.set_xlim(-0.5, len(all_quarters) - 0.5)

    plt.savefig(output_path, dpi=300, bbox_inches='tight', facecolor='white')
    print(f"✅ 이미지 저장 완료: {output_path}")
    plt.show()

# ==============================================================================
# [실행부]
# ==============================================================================
file_path = 'tagged_result_final_v26_cleansed.csv'

# 1. 데이터 로드 및 AI 키워드 추출
df_ai, start_date, end_date = load_and_preprocess_ai_data(file_path)

# 2. 플랫폼 순서 및 색상 정의
platforms_order = ['네이버블로그', '디시인사이드', '네이버카페', '에펨코리아', '더쿠']
platforms_colors = {
    '네이버블로그': '#2DB400',
    '디시인사이드': '#3b5a99',
    '네이버카페': '#00C73C',
    '에펨코리아': '#4682B4',
    '더쿠': '#D81B60'
}

print(">>> 플랫폼별 AI 언급량 추이 시각화 시작")

# 3. 데이터 집계
trend_data, all_quarters = prepare_platform_trend(df_ai, start_date, end_date, platforms_order)

# 4. 시각화 실행
plot_horizontal_trends(trend_data, platforms_colors, 'platform_ai_trend_horizontal.png', all_quarters)

"""##### 후기 데이터"""

# ==============================================================================
# [Step 1] 데이터 로드 및 전처리 (AI 키워드 추출 및 날짜 필터링)
# ==============================================================================
def load_and_preprocess_ai_data(file_path):
    df = pd.read_csv(file_path)
    df['whole_content'] = df['whole_content'].fillna('').astype(str)

    # 1. 날짜 데이터
    df['date'] = pd.to_datetime(df['작성날짜'], errors='coerce')

    # ★ 2022년 11월 1일 이후 데이터만 남기기
    df = df[df['date'] >= '2022-11-01']
    print(f"✅ 2022년 11월 이후 분석 대상 데이터: {len(df):,}건")

    # 2. 분기(Quarter) 단위 변환
    df['Period'] = df['date'].dt.to_period('Q')

    # 3. 사이트 칼럼을 Platform으로 복사
    if 'Platform' not in df.columns:
        df['Platform'] = df['사이트']

    # '기타' 플랫폼 제외
    df = df[df['Platform'] != '기타']

    # 4. AI 서비스 키워드 추출
    target_ai_keywords = {
        'GPT': ['gpt', 'Gpt', '지피티', 'GPT', '챗지피티', 'chatgpt'],
        '뤼튼': ['뤼튼', 'wrtn'],
        'Claude': ['Claude', '클로드'],
        'Gemini': ['Gemini', '제미나이', '재미나이'],
        'Grok': ['Grok', '그록'],
        '기타': ['ai 사주', 'ai사주', 'ai운세', 'ai 운세', 'ai타로', 'ai 타로', 'ai 신점', 'ai신점']
    }

    def extract_ai_keyword(text):
        text_lower = str(text).lower()
        found_ais = []
        for ai_name, keywords in target_ai_keywords.items():
            for kw in keywords:
                if kw.lower() in text_lower:
                    found_ais.append(ai_name)
                    break
        if not found_ais:
            return None
        return found_ais[0]

    print(">>> AI 키워드 추출 중...")
    df['AI_Service'] = df['whole_content'].apply(extract_ai_keyword)

    # AI 키워드가 언급된 데이터만 필터링
    df_ai = df.dropna(subset=['AI_Service']).copy()
    print(f"✅ AI 키워드 언급 데이터 추출 완료: {len(df_ai):,}건")

    # X축(분기) 고정을 위한 시작/종료일 설정 (22년 11월이 포함된 22년 4분기부터 시작)
    start_date = "2019-01-01"
    end_date = "2025-09-30"

    return df_ai, start_date, end_date

# ==============================================================================
# [Step 2] 분기별/플랫폼별 전체 AI 게시글 수 집계
# ==============================================================================
def prepare_platform_trend(df, start_date, end_date, platforms_order):
    # 플랫폼별/분기별 게시글 수 집계 (AI 서비스 총합)
    quarterly_counts = df.groupby(['Platform', 'Period']).size().unstack(fill_value=0)

    # 기간 내 모든 분기를 컬럼으로 확보
    all_quarters = pd.period_range(start=start_date, end=end_date, freq='Q')
    quarterly_counts = quarterly_counts.reindex(columns=all_quarters, fill_value=0)

    # 지정된 플랫폼 순서대로 정렬 (누락된 플랫폼은 0으로 채움)
    quarterly_counts = quarterly_counts.reindex(platforms_order, fill_value=0)

    return quarterly_counts, all_quarters

# ==============================================================================
# [Step 3] 시각화 함수 (비대칭 2-top, 3-bottom 배치 적용)
# ==============================================================================
def plot_horizontal_trends(data_df, platform_colors, output_path, all_quarters):
    from matplotlib.gridspec import GridSpec

    platforms = data_df.index.tolist()

    # 전체 캔버스 설정
    fig = plt.figure(figsize=(24, 14), constrained_layout=True)

    # GridSpec 설정: 상단 1.2, 하단 1.0 비율로 2행 6열 생성
    gs = GridSpec(2, 6, figure=fig, height_ratios=[1.2, 1.0])

    # 상단 2개 그래프 (각각 3열씩 넓게 차지)
    ax1 = fig.add_subplot(gs[0, 0:3])
    ax2 = fig.add_subplot(gs[0, 3:6])

    # 하단 3개 그래프 (각각 2열씩 차지)
    ax3 = fig.add_subplot(gs[1, 0:2])
    ax4 = fig.add_subplot(gs[1, 2:4])
    ax5 = fig.add_subplot(gs[1, 4:6])

    axes = [ax1, ax2, ax3, ax4, ax5]

    # 동적 X축 라벨 생성 (예: '23 1Q)
    x_labels = [f"'{str(q.year)[2:]} {q.quarter}Q" for q in all_quarters]

    for idx, (ax, platform) in enumerate(zip(axes, platforms)):
        color_code = platform_colors.get(platform, '#999999')

        row_data = data_df.iloc[idx].values
        numeric_data = pd.to_numeric(row_data, errors='coerce')
        x = np.arange(len(numeric_data))

        mask = ~np.isnan(numeric_data)
        valid_x = x[mask]
        valid_data = numeric_data[mask]

        # 상단과 하단 그래프의 폰트 및 선 굵기를 다르게 설정
        if idx < 2:  # 상단 그래프
            title_fs = 26      # 하단 플랫폼 이름(n=) 폰트
            anno_fs = 18       # 최고/최저점 숫자 폰트
            tick_fs = 15       # X축 연도 폰트
            line_w = 4         # 상단은 선 굵기도 살짝 두껍게
        else:        # 하단 그래프
            title_fs = 20
            anno_fs = 14
            tick_fs = 13
            line_w = 3

        # 스플라인 곡선 (부드럽게)
        if len(valid_data) > 3 and valid_data.max() > 0:
            try:
                x_smooth = np.linspace(valid_x.min(), valid_x.max(), 300)
                spl = make_interp_spline(valid_x, valid_data, k=3)
                y_smooth = np.clip(spl(x_smooth), 0, None)
                ax.fill_between(x_smooth, y_smooth, 0, color=color_code, alpha=0.2)
                ax.plot(x_smooth, y_smooth, color=color_code, linewidth=line_w)
            except:
                ax.fill_between(valid_x, valid_data, 0, color=color_code, alpha=0.2)
                ax.plot(valid_x, valid_data, color=color_code, linewidth=line_w)
        else:
            ax.fill_between(valid_x, valid_data, 0, color=color_code, alpha=0.2)
            ax.plot(valid_x, valid_data, color=color_code, linewidth=line_w)

        # 최고/최저값 텍스트 표시
        if len(valid_data) > 0 and valid_data.max() > 0:
            max_idx = np.argmax(valid_data)
            min_idx = np.argmin(valid_data)
            max_val = valid_data[max_idx]
            min_val = valid_data[min_idx]
            max_x_pos = valid_x[max_idx]
            min_x_pos = valid_x[min_idx]

            disp_max = f"{int(max_val):,}"
            disp_min = f"{int(min_val):,}"

            ax.annotate(disp_max, (max_x_pos, max_val),
                        textcoords="offset points", xytext=(0, 10),
                        ha='center', fontsize=anno_fs, fontweight='bold', color=color_code)

            ax.annotate(disp_min, (min_x_pos, min_val),
                        textcoords="offset points", xytext=(0, -15),
                        ha='center', fontsize=anno_fs, fontweight='bold', color=color_code)

        # 플랫폼 이름 (하단 중앙) - 다단 배치 시 겹치지 않도록 위치 미세 조정 (-0.15)
        total_n = int(valid_data.sum()) if len(valid_data) > 0 else 0
        ax.text(0.5, -0.15, f"{platform}\n(n={total_n:,})", transform=ax.transAxes,
                ha='center', va='top', fontsize=title_fs, fontweight='bold')

        # ★ X축 눈금 원복 (2019 ~ 2025, 분기 표기 생략)
        years = ['19', '20', '21', '22', '23', '24', '25']
        ticks = [i*4 for i in range(len(years))]
        valid_ticks = [t for t in ticks if t < len(numeric_data)]
        valid_labels = [years[i] for i, t in enumerate(ticks) if t < len(numeric_data)]

        ax.set_xticks(valid_ticks)
        ax.set_xticklabels(valid_labels, fontsize=tick_fs, color='gray')

        # Y축 범위 여유있게 (텍스트가 잘리지 않도록 1.35로 살짝 상향)
        if len(valid_data) > 0 and valid_data.max() > 0:
            y_max = np.nanmax(valid_data)
            ax.set_ylim(0, y_max * 1.35)
        else:
            ax.set_ylim(0, 10)

        # 디자인 깔끔하게 (Spine 제거)
        for spine in ax.spines.values():
            spine.set_visible(False)
        ax.tick_params(axis='x', length=0, pad=10)
        ax.set_yticks([])

        # X축 좌우 여백 설정 (분기 수에 맞춰 동적 조절)
        ax.set_xlim(-0.5, len(all_quarters) - 0.5)

    plt.savefig(output_path, dpi=300, bbox_inches='tight', facecolor='white')
    print(f"✅ 이미지 저장 완료: {output_path}")
    plt.show()

# ==============================================================================
# [실행부]
# ==============================================================================
file_path = 'filtered_reviews_data_v26_cleansed.csv'

# 1. 데이터 로드 및 AI 키워드 추출
df_ai, start_date, end_date = load_and_preprocess_ai_data(file_path)

# 2. 플랫폼 순서 및 색상 정의
platforms_order = ['네이버블로그', '디시인사이드', '네이버카페', '에펨코리아', '더쿠']
platforms_colors = {
    '네이버블로그': '#2DB400',
    '디시인사이드': '#3b5a99',
    '네이버카페': '#00C73C',
    '에펨코리아': '#4682B4',
    '더쿠': '#D81B60'
}

print(">>> 플랫폼별 AI 언급량 추이 시각화 시작")

# 3. 데이터 집계
trend_data, all_quarters = prepare_platform_trend(df_ai, start_date, end_date, platforms_order)

# 4. 시각화 실행
plot_horizontal_trends(trend_data, platforms_colors, 'platform_ai_trend_horizontal.png', all_quarters)