# -*- coding: utf-8 -*-
"""filter_reviews

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C1zoByrlt6K5kuBdcJdKo8-vhpZVk-2-

# 데이터 분류

### 1. 규칙 기반 분류(광고/맥락/유형/의도)
"""

import pandas as pd
import re

file_path = 'final_data_2019_2025_cleansed.csv'
save_path = 'tagged_result_final_v26_cleansed.csv'

try:
    df = pd.read_csv(file_path)

    # [0] 텍스트 전처리
    df['target_text'] = df['whole_content'].fillna('').astype(str)

    def clean_text(text):
        text = re.sub(r'[-–\s]*dc\s*(official|app)[\w\s]*', '', text, flags=re.IGNORECASE)
        text = re.sub(r'[-–\s]*(official|app)\s*dc[\w\s]*', '', text, flags=re.IGNORECASE)
        text = re.sub(r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', '', text)
        return text

    df['target_text'] = df['target_text'].apply(clean_text)

    # ===========================================================
    # [1] 광고 키워드 (기존 키워드 100% 유지)
    # ===========================================================
    keywords_ad = [
        '원고료', '광고주로부터', '업체로부터 제공', '업체로 부터 제공', '업체로 부터 지원', '업체로부터 지원', '업체로부터 무료로',
        '기업으로부터 제공', '기업으로 부터 제공', '기업으로부터 지원', '기업으로 부터 지원', '포인트를 지급',
        '협찬', '체험단', '쿠팡 파트너스', '포인트지급 후', '포인트 지급 후', '상담을 제공받', '기회를 제공받',
        '지원받아 작성', '지원을 받아 작성', '제공받고 작성', '제공받아 작성', '서비스를 제공받', '​이용권을 제공', '수수료를 제공',
        '레뷰를 통해', '링블를 통해', '티블을 통해', '시원뷰를 통해',
        '상담문의', '예약문의', '문의환영', '문의바람', '문의 주세요', '문의주세요', '문의해 주세요', '문의해주세요',
        '상담신청', '예약신청', 'bit.ly', 'pf.kakao'
    ]
    def classify_ad(text): return any(k in text for k in keywords_ad)

    # ===========================================================
    # [2] 오락 및 일상 맥락 (기존 키워드 100% 유지)
    # ===========================================================
    keywords_travel = ['여행', '일본', '도쿄', '대만', '휴가', '호텔', '리조트', '게하', '관광', '투어', '숙소', '1박', '2박', '후쿠오카', '다자이후']
    keywords_pub = ['술집', '포차', '이자카야', '헌팅', '라운지', '클럽', '주점']
    keywords_daily = ['일기', '일상', '데일리', '블챌', '맛집', '삼겹살', '커피', '에이드', '먹방', '데이트', '영화', '쇼핑', '출근', '퇴근', '알바', '운동']

    def classify_context(text):
        if any(k in text for k in keywords_travel): return '여행'
        elif any(k in text for k in keywords_pub): return '술집'
        elif any(k in text for k in keywords_daily): return '일상'
        else: return '운세집중'

    # ===========================================================
    # [3] 온라인 운세 서비스 채널 분류
    # ===========================================================
    keywords_platform_human = ['사주나루', '홍카페', '천명', '네이버 엑스퍼트', '엑스퍼트', 'expert',
                               '사주천궁', '운세7', '운세담다', '타로문', '더사주']

    # [수정됨] 기존 keywords_app_ai를 두 그룹으로 분리

    # 1. AI 및 대화형 챗봇 (범용 AI + 대화형 운세 서비스)
    # 헬로우봇, 판밍밍, 라비 등 대화형 인터페이스를 사용하는 서비스를 이쪽으로 분류합니다.
    keywords_ai_gen = [
        'AI', '인공지능', 'gpt', 'Gpt', '지피티', 'GPT', '뤼튼', 'wrtn', '클로드', 'Claude',
        'Gemini', '제미나이', '재미나이', 'Grok', '그록', '챗봇',
        '헬로우봇', '판밍밍', '라비', '에이닷'  # <--- 대화형 서비스 추가
    ]

    # 2. 모바일 앱 (조회형/리포트형 서비스)
    keywords_app_fortune = [
        '점신', '포스텔러', '백점', '운세의신', '운세의 신', '만세력 천을귀인', '만세력천을귀인', '사주어플', '사주 어플', '사주앱', '사주 앱',
        '운세어플', '운세 어플', '운세앱', '운세 앱', '타로 어플', '타로어플', '타로앱', '타로 앱'
        # '강남'은 판밍밍과 붙어 나오는 경우가 많으나, 독립적인 앱 키워드로도 남겨둡니다.
    ]

    # 3. 확실한 이동 동사 (Offline Movement)
    keywords_offline_movement = ['직접 가', '직접가', '갔다', '가보고', '가 보고', '가보니', '가 보니', '다녀', '보고 가', '보고가',
                                 '발품', '찾아가', '현장', '방문상담', '방문 상담', '방문 후기', '방문후기', '방문했', '방문하', '방문한', '방문해']

    # 4. 온라인/원격 수단 (Online Method)
    keywords_online_explicit = [
        '온라인', '화상', '비대면', '줌', 'zoom',
        '카톡', '카카오톡', '채팅', '오픈톡', '오픈 톡', '옵챗', '전화 운세', '전화운세',
        '전화상담', '전화 상담', '전화 사주', '전화사주', '전화 타로', '전화타로', '전화 신점', '전화신점', '통화', '보이스',
        '문자', '메일', '이메일', '쪽지', '디엠', 'dm', 'DM'
    ]

    # 5. 오프라인 장소 명사 (Offline Place Noun)
    keywords_offline_places = ['철학관', '철학원', '점집', '타로집', '신당', '골목', '간판', '위치', '사주카페', '사주 카페', '타로카페', '타로 카페', '오프라인', '무당']

    # 6. 포텔/금융/생활앱
    keywords_app_general = [
        '신한생명', '삼성생명', '신한라이프', '신한은행', '국민은행', '우리은행', '농협',
        '신한카드', '국민카드', '우리카드', 'BC카드',
        '토스', 'toss', '신한 쏠', '신한쏠', 'kb스타뱅킹', '모니모', '캐시워크', '우리WON뱅킹', '페이북',
        '네이버 무료', '다음 무료', '네이트 무료', '뽐뿌 무료',
        '네이버 운세', '네이버운세', '다음운세', '다음 운세', '네이트운세', '네이트 운세', '뽐뿌운세', '뽐뿌 운세'
    ]

    # 7. 기타 어플
    keywords_general_app = ['어플', '앱', '설치', '깔아', '다운', '결제', '코인', '충전', '스토어', '다운', '바로보기']

    # 8. 나머지
    keywords_media_youtube = ['유튜브', '유투브', '채널', 'youtube', '유튜버', '영상', '구독', '강의', '쇼츠', 'BJ']
    keywords_passive = ['라더라', '다더라', '들었', '해주심', '나왔대', '말해줌', '용하다는']


    def classify_channel(text, intent_prediction):
        # 1. 전문가 플랫폼/앱 (최우선)
        if any(k in text for k in keywords_platform_human): return '상담플랫폼(사주나루/홍카페 등)'

        # [수정] AI와 앱 분리하여 태깅
        if any(k in text for k in keywords_ai_gen): return 'AI(ChatGPT/챗봇 등)'
        if any(k in text for k in keywords_app_fortune): return '모바일앱(점신/포스텔러 등)'

        # 2. [★핵심] "이동(갔다/방문)"이 있으면 -> 온라인 단어가 있어도 오프라인 승리
        if any(k in text for k in keywords_offline_movement):
            if intent_prediction == '자가분석/이론토론': return '오프라인/방문'
            return '오프라인/방문'

        # 3. 이동은 없는데 "온라인/카톡/전화"가 있다 -> 원격상담 승리
        if any(k in text for k in keywords_online_explicit): return '원격/온라인 상담'

        # 4. 앱/웹 체크
        if any(k in text for k in keywords_app_general): return '포털/금융/생활앱'
        if '유튜브' in text or '영상' in text or '채널' in text: return '유튜브/영상'
        if any(k in text for k in keywords_general_app): return '기타어플'

        # 5. [★핵심] 이동은 없지만 "장소(점집)"만 있다 -> 오프라인 추정
        if any(k in text for k in keywords_offline_places):
            if intent_prediction == '자가분석/이론토론': return '전문가(채널미상)'
            return '오프라인/방문'

        # 6. 나머지
        if intent_prediction == '자가분석/이론토론': return '독학/웹검색'
        if intent_prediction == '해석요청/상담': return '커뮤니티(댓글품앗이)'
        if any(k in text for k in keywords_passive): return '전문가(채널미상)'

        return '기타/미상'

    # ===========================================================
    # [4] 사용자 의도 (기존 키워드 100% 유지)
    # ===========================================================
    keywords_intent_review = ['후기', '썰', '맞춘', '맞힌', '용하', '소름', '틀린', '안 맞', '맞음', '비추', '추천', '만족', '사기', '쪽집게']
    keywords_intent_venting = ['힘들다', '힘들어', '괴롭', '우울', '죽고싶', '자살', '망했', '백수', '퇴사', '이별', '헤어', '비나이다', '제발', '합격', '기원', '기도']

    keywords_intent_study = [
        '만세력', '천을귀인', '일주', '용신', '기신', '대운', '격국', '임상', '명리', '이론', '내사주', '시주', '월주', '년주', '건명', '곤명', '합화', '카드', '덱',
        '별자리', '행성', '하우스', '상승점', '태양', '수성', '금성', '화성', '목성', '토성', '천왕성', '해왕성', '명왕성', '조디악', '사인',
        '통변', '인비다', '재다', '관다', '식상', '다자', '일간', '신강', '신약', '사주 분석'
    ]

    keywords_intent_request = ['봐주세요', '봐주실', '봐줘', '해석좀', '해석부탁', '해석 부탁', '인가요?', '건가요?', '맞나요?', '가능한가요', '괜찮음?', '풀이좀', '어때', '어떤가', '봐주라', '무슨 뜻', '뭔지', '좀 봐']
    keywords_intent_info = ['어디가', '위치', '비용', '가격', '얼마', '유명한', '잘보는', '알려줘']
    keywords_intent_light = ['오늘의 운세', '오늘의운세', '오운', '신년운세', '신년 운세', '새해 운세', '토정비결', '띠별', '운세뽑기', '운세 뽑기']


    def classify_intent(text):
        if any(k in text for k in keywords_intent_review): return '경험공유/검증'
        if any(k in text for k in keywords_intent_venting): return '신세한탄/소원'
        if any(k in text for k in keywords_intent_light): return '단순조회/시즈널'

        has_study = any(k in text for k in keywords_intent_study)
        has_req = any(k in text for k in keywords_intent_request)

        if has_study and not has_req: return '자가분석/이론토론'
        if has_req: return '해석요청/상담'
        if any(k in text for k in keywords_intent_info): return '정보탐색/질문'
        if has_study: return '자가분석/이론토론'

        return '단순잡담/기타'

    def classify_intent_refined(text, predicted_channel, predicted_context, current_intent):
        if predicted_context == '여행' or predicted_channel == '오프라인/방문' or current_intent == '자가분석/이론토론':
            return current_intent

        if predicted_channel == '포털/금융/생활앱' and current_intent == '경험공유/검증':
            strong_words = ['용하', '소름', '사기', '돈날', '쪽집게', '신점', '공수', '잘 맞', '깜짝', '맞추']
            if not any(k in text for k in strong_words):
                 return '단순조회/시즈널'

        return current_intent

    # ===========================================================
    # [실행] 통합 보정 로직 (v26)
    # ===========================================================
    print("★ v26 통합 보정 로직 실행")

    df['is_ad'] = df['target_text'].apply(classify_ad)
    df['context_type'] = df['target_text'].apply(classify_context)

    # 1. 임시 의도 분류
    df['temp_intent'] = df['target_text'].apply(classify_intent)

    # 2. 채널 분류 (업데이트된 함수 사용)
    df['channel_type'] = df.apply(lambda x: classify_channel(x['target_text'], x['temp_intent']), axis=1)

    # 3. 최종 의도 보정
    df['user_intent'] = df.apply(lambda x: classify_intent_refined(x['target_text'], x['channel_type'], x['context_type'], x['temp_intent']), axis=1)

    del df['temp_intent']
    del df['target_text']

    df.to_csv(save_path, index=False, encoding='utf-8-sig')

    print("★ 작업 완료 ★")
    print("\n[광고 분포]\n", df['is_ad'].value_counts())
    print("\n[오락 맥락 분포]\n", df['context_type'].value_counts())
    print("\n[이용 채널 분포]\n", df['channel_type'].value_counts())
    print("\n[사용자 의도 분포]\n", df['user_intent'].value_counts())
    print(f"파일이 저장되었습니다: {save_path}")

except Exception as e:
    print(f"에러 발생: {e}")

"""### 2. 온라인 운세 서비스 후기 데이터 분류"""

# [0] 폰트 및 라이브러리 설정
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.font_manager as fm
import math
import os

# 1. 폰트 설정
plt.rc('font', family='NanumBarunGothic')
plt.rcParams['axes.unicode_minus'] = False

# 2. 데이터 로드 (v26 파일)
file_path = 'tagged_result_final_v26_cleansed.csv'
# ★ [추가됨] 최종 데이터를 저장할 경로와 파일명 설정
save_path = 'filtered_reviews_data_v26_cleansed.csv'

df = pd.read_csv(file_path)
df['whole_content'] = df['whole_content'].fillna('').astype(str)

# ------------------------------------------------------------------------------
# [Step 1] 데이터 전처리 및 필터링
# ------------------------------------------------------------------------------
print(">>> 데이터 전처리 및 필터링 중...")

# 1. 광고 및 맥락 필터링
if 'is_ad' in df.columns:
    df_pure = df[(df['is_ad'] == False) | (df['is_ad'] == 'False')]
else:
    df_pure = df.copy()

excluded_contexts = ['여행', '술집']
df_pure = df_pure[~df_pure['context_type'].isin(excluded_contexts)]

# 2. 사용자 의도(Intent) 필터링
target_intents = ['경험공유/검증', '신세한탄/소원', '해석요청/상담', '단순조회/시즈널']
df_pure = df_pure[df_pure['user_intent'].isin(target_intents)]

# 3. 분석 대상 채널 필터링 (기존 7개 채널 유지)
target_analysis_channels = [
    '모바일앱(점신/포스텔러 등)',
    'AI(ChatGPT/챗봇 등)',
    '원격/온라인 상담',
    '상담플랫폼(사주나루/홍카페 등)',
    '포털/금융/생활앱',
    '유튜브/영상',
    '기타어플'
]
df_pure = df_pure[df_pure['channel_type'].isin(target_analysis_channels)]

print(f"✅ 최종 분석 데이터(채널 필터링 완료): {len(df_pure):,}건")

# ------------------------------------------------------------------------------
# [Step 2] ★ 추가됨: 최종 분석 데이터 파일로 저장
# ------------------------------------------------------------------------------
print("\n💾 정제된 최종 분석 데이터를 저장하는 중...")

# 한글 깨짐 방지를 위해 encoding='utf-8-sig' 적용
df_pure.to_csv(save_path, index=False, encoding='utf-8-sig')

print("="*50)
print(f"✅ 데이터 저장 완료!")
print(f"   저장 경로: {save_path}")
print("="*50)